using System;
using System.Data;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using CrystalDecisions.CrystalReports.Engine;

public partial class RoportForms_ADD_SaleSummaryCustomerwise : System.Web.UI.Page
{
    DatabaseAccessLayer DL_DBAccess = null;
    public static string type = "";

    protected void Page_Load(object sender, EventArgs e)
    {
        HtmlGenericControl home = (HtmlGenericControl)this.Page.Master.FindControl("Menus").FindControl("PPC");
        home.Attributes["class"] = "active";
        HtmlGenericControl home1 = (HtmlGenericControl)this.Page.Master.FindControl("Menus").FindControl("PPCMV");
        home1.Attributes["class"] = "active";
    }

    #region Page_Init
    protected void Page_Init(object sender, EventArgs e)
    {
        try
        {
            string Title = Request.QueryString[0];
            type = Request.QueryString[2].ToString();
            string cond = Request.QueryString[1].ToString();
            GenerateReport(Title, type, cond);
            //Assign Perticular Title
            lbltitle.Text = Title;
            Page.Title = Title;
        }
        catch (Exception)
        {

        }
    }
    #endregion

    #region GenerateReport
    private void GenerateReport(string Title, string type, string cond)
    {
        try
        {
            DL_DBAccess = new DatabaseAccessLayer();
            string Query = "";
            //Query = "SELECT ITEM_MASTER.I_CODENO, ITEM_MASTER.I_NAME, SO_TYPE_MASTER.SO_T_SHORT_NAME, CUSTPO_DETAIL.CPOD_ORD_QTY, CUSTPO_DETAIL.CPOD_RATE,  CUSTPO_DETAIL.CPOD_AMT, CUSTPO_DETAIL.CPOD_CUST_I_NAME, CUSTPO_DETAIL.CPOD_CUST_I_CODE, CUSTPO_DETAIL.CPOD_AMORTRATE,CUSTPO_DETAIL.CPOD_DISPACH,ITEM_UNIT_MASTER.I_UOM_NAME,CUSTPO_MASTER.CPOM_PONO,CUSTPO_MASTER.CPOM_DOC_NO,CUSTPO_MASTER.CPOM_DATE, CUSTPO_MASTER.CPOM_BASIC_AMT, PROJECT_CODE_MASTER.PROCM_NAME, PARTY_MASTER.P_NAME FROM PARTY_MASTER INNER JOIN SO_TYPE_MASTER INNER JOIN CUSTPO_MASTER ON SO_TYPE_MASTER.SO_T_CODE = CUSTPO_MASTER.CPOM_TYPE INNER JOIN PROJECT_CODE_MASTER ON CUSTPO_MASTER.CPOM_PROJECT_CODE = PROJECT_CODE_MASTER.PROCM_CODE ON  PARTY_MASTER.P_CODE = CUSTPO_MASTER.CPOM_P_CODE INNER JOIN ITEM_UNIT_MASTER INNER JOIN ITEM_MASTER INNER JOIN CUSTPO_DETAIL ON ITEM_MASTER.I_CODE = CUSTPO_DETAIL.CPOD_I_CODE ON ITEM_UNIT_MASTER.I_UOM_CODE = ITEM_MASTER.I_UOM_CODE ON  CUSTPO_MASTER.CPOM_CODE = CUSTPO_DETAIL.CPOD_CPOM_CODE WHERE " + cond + " (ITEM_UNIT_MASTER.ES_DELETE = 0) AND (ITEM_MASTER.ES_DELETE = 0) AND (CUSTPO_MASTER.ES_DELETE = 0) AND (PROJECT_CODE_MASTER.ES_DELETE = 0) AND (SO_TYPE_MASTER.ES_DELETE = 0) and (PARTY_MASTER.ES_DELETE=0)";
            //Query = "SELECT ITEM_MASTER.I_CODE, ITEM_MASTER.I_NAME, ITEM_MASTER.I_CODENO, CUSTPO_DETAIL.CPOD_RATE, GROUP_MASTER.GP_NAME, ITEM_MASTER.I_WEIGHT FROM CUSTPO_MASTER INNER JOIN ITEM_MASTER INNER JOIN PRODUCT_MASTER INNER JOIN GROUP_MASTER ON PRODUCT_MASTER.PROD_GP_CODE = GROUP_MASTER.GP_CODE ON ITEM_MASTER.I_CODE = PRODUCT_MASTER.PROD_I_CODE INNER JOIN CUSTPO_DETAIL ON ITEM_MASTER.I_CODE = CUSTPO_DETAIL.CPOD_I_CODE ON CUSTPO_MASTER.CPOM_CODE = CUSTPO_DETAIL.CPOD_CPOM_CODE WHERE " + cond + " (CUSTPO_MASTER.ES_DELETE = 0) AND (ITEM_MASTER.I_CM_COMP_ID = 1) AND (ITEM_MASTER.ES_DELETE = 0) AND (ITEM_MASTER.I_CAT_CODE = '-2147483648') and PRODUCT_MASTER.ES_DELETE=0 and GROUP_MASTER.ES_DELETE=0 ORDER BY ITEM_MASTER.I_CODENO";
            if (type == "Cust")
            {
                //Query = "SELECT PARTY_MASTER.P_NAME, sum(CUSTPO_DETAIL.CPOD_AMT) as CPOD_AMT,'' as TONNAGE,'' as REMARK FROM PARTY_MASTER INNER JOIN CUSTPO_MASTER INNER JOIN CUSTPO_DETAIL ON CUSTPO_MASTER.CPOM_CODE = CUSTPO_DETAIL.CPOD_CPOM_CODE ON PARTY_MASTER.P_CODE = CUSTPO_MASTER.CPOM_P_CODE WHERE  (CUSTPO_MASTER.ES_DELETE = 0) " + cond + " and PARTY_MASTER.ES_DELETE=0 group by P_NAME order by P_NAME";
                // Commented By Mahesh
                //Query = "SELECT SUM(INVOICE_MASTER.INM_NET_AMT) AS CPOD_AMT, PARTY_MASTER.P_CODE, PARTY_MASTER.P_NAME FROM CUSTPO_DETAIL INNER JOIN CUSTPO_MASTER ON CUSTPO_DETAIL.CPOD_CPOM_CODE = CUSTPO_MASTER.CPOM_CODE INNER JOIN INVOICE_MASTER INNER JOIN INVOICE_DETAIL ON INVOICE_MASTER.INM_CODE = INVOICE_DETAIL.IND_INM_CODE ON CUSTPO_MASTER.CPOM_CODE = INVOICE_DETAIL.IND_CPOM_CODE AND CUSTPO_DETAIL.CPOD_I_CODE = INVOICE_DETAIL.IND_I_CODE INNER JOIN PARTY_MASTER ON INVOICE_MASTER.INM_P_CODE = PARTY_MASTER.P_CODE WHERE (INVOICE_MASTER.ES_DELETE = 0) " + cond + "  AND (INVOICE_MASTER.INM_TYPE = 'TAXINV') AND (INVOICE_MASTER.INM_IS_SUPPLIMENT = 0) GROUP BY PARTY_MASTER.P_CODE, PARTY_MASTER.P_NAME";
                //Query = "SELECT P.P_CODE,P.P_NAME,ISNULL(SUM(CS_SCHEDULE_QTY),0) as CS_SCHEDULE_QTY, ISNULL(CUSTPO_DETAIL.CPOD_RATE,0) AS CPOD_RATE,ISNULL(I_TARGET_WEIGHT,0) as PROD_FINISH_WT FROM CUSTPO_MASTER INNER JOIN ITEM_MASTER INNER JOIN PRODUCT_MASTER INNER JOIN GROUP_MASTER ON PRODUCT_MASTER.PROD_GP_CODE = GROUP_MASTER.GP_CODE ON ITEM_MASTER.I_CODE = PRODUCT_MASTER.PROD_I_CODE INNER JOIN CUSTPO_DETAIL ON ITEM_MASTER.I_CODE = CUSTPO_DETAIL.CPOD_I_CODE ON CUSTPO_MASTER.CPOM_CODE = CUSTPO_DETAIL.CPOD_CPOM_CODE INNER JOIN CUSTOMER_SCHEDULE C ON PRODUCT_MASTER.PROD_I_CODE=C.CS_I_CODE inner join PARTY_MASTER P ON CPOM_P_CODE=P.P_CODE WHERE " + cond + " C.ES_DELETE =0 AND P.ES_DELETE =0 AND (CUSTPO_MASTER.ES_DELETE = 0) AND (ITEM_MASTER.I_CM_COMP_ID = '" + Session["CompanyID"].ToString() + "') AND (ITEM_MASTER.ES_DELETE = 0) AND (ITEM_MASTER.I_CAT_CODE = '-2147483648') and PRODUCT_MASTER.ES_DELETE=0 and GROUP_MASTER.ES_DELETE=0 GROUP BY P.P_CODE,P.P_NAME,CPOD_RATE,I_TARGET_WEIGHT ORDER BY P.P_NAME ";
                //Query = "SELECT P.P_CODE,P.P_NAME,sum(ISNULL(CS_SCHEDULE_QTY,0)) as CS_SCHEDULE_QTY,ISNULL(I_TARGET_WEIGHT,0) as PROD_FINISH_WT ,I_INV_RATE AS CPOD_RATE FROM ITEM_MASTER INNER JOIN PRODUCT_MASTER INNER JOIN GROUP_MASTER ON PRODUCT_MASTER.PROD_GP_CODE = GROUP_MASTER.GP_CODE ON ITEM_MASTER.I_CODE = PRODUCT_MASTER.PROD_I_CODE INNER JOIN CUSTOMER_SCHEDULE C ON PRODUCT_MASTER.PROD_I_CODE=C.CS_I_CODE INNER JOIN PARTY_MASTER P ON C.CS_P_CODE=P.P_CODE WHERE " + cond + " C.ES_DELETE =0 AND P.ES_DELETE =0 AND (ITEM_MASTER.I_CM_COMP_ID = '" + Session["CompanyID"].ToString() + "') AND (ITEM_MASTER.ES_DELETE = 0) AND (ITEM_MASTER.I_CAT_CODE = '-2147483648') and PRODUCT_MASTER.ES_DELETE=0 and GROUP_MASTER.ES_DELETE=0 group by P.P_CODE,P.P_NAME,I_TARGET_WEIGHT,GP_NAME,I_INV_RATE ORDER BY P.P_NAME ";
                //Query = "SELECT P.P_CODE,P.P_NAME,sum(ISNULL(CS_SCHEDULE_QTY,0)) as CS_SCHEDULE_QTY,ISNULL(I_TARGET_WEIGHT,0) as PROD_FINISH_WT ,I_INV_RATE AS CPOD_RATE into #Temp FROM ITEM_MASTER INNER JOIN PRODUCT_MASTER INNER JOIN GROUP_MASTER ON PRODUCT_MASTER.PROD_GP_CODE = GROUP_MASTER.GP_CODE ON ITEM_MASTER.I_CODE = PRODUCT_MASTER.PROD_I_CODE INNER JOIN CUSTOMER_SCHEDULE C ON PRODUCT_MASTER.PROD_I_CODE=C.CS_I_CODE INNER JOIN PARTY_MASTER P ON C.CS_P_CODE=P.P_CODE WHERE " + cond + " C.ES_DELETE =0 AND P.ES_DELETE =0 AND (ITEM_MASTER.I_CM_COMP_ID = '" + Session["CompanyID"].ToString() + "') AND (ITEM_MASTER.ES_DELETE = 0) AND (ITEM_MASTER.I_CAT_CODE = '-2147483648') and PRODUCT_MASTER.ES_DELETE=0 and GROUP_MASTER.ES_DELETE=0 group by P.P_CODE,P.P_NAME,I_TARGET_WEIGHT,GP_NAME,I_INV_RATE ORDER BY P.P_NAME select P_CODE,P_NAME, sum(isnull(CS_SCHEDULE_QTY,0)) as CS_SCHEDULE_QTY,sum(isnull(PROD_FINISH_WT,0)) as PROD_FINISH_WT,sum(isnull(CPOD_RATE,0)) as CPOD_RATE from #Temp group by P_CODE,P_NAME ORDER BY P_NAME drop table #Temp";
                //Query = "SELECT P.P_CODE,P.P_NAME,isnull((isnull((select SUM(ISNULL(CS_SCHEDULE_QTY,0)) FROM CUSTOMER_SCHEDULE where " + cond + " CUSTOMER_SCHEDULE.CS_I_CODE=I_CODE and CUSTOMER_SCHEDULE.ES_DELETE=0),0) *  ISNULL(I_INV_RATE,0)),0)/100000 as CS_SCHEDULE_QTY,ISNULL(I_TARGET_WEIGHT,0) as PROD_FINISH_WT ,I_INV_RATE AS CPOD_RATE1 , isnull((isnull((select SUM(ISNULL(CS_SCHEDULE_QTY,0)) FROM CUSTOMER_SCHEDULE where " + cond + " CUSTOMER_SCHEDULE.CS_I_CODE=I_CODE and CUSTOMER_SCHEDULE.ES_DELETE=0 ),0) * ISNULL(I_TARGET_WEIGHT,0) ),0)/1000 as CPOD_RATE into #Temp FROM ITEM_MASTER INNER JOIN PRODUCT_MASTER INNER JOIN GROUP_MASTER ON PRODUCT_MASTER.PROD_GP_CODE = GROUP_MASTER.GP_CODE ON ITEM_MASTER.I_CODE = PRODUCT_MASTER.PROD_I_CODE INNER JOIN CUSTOMER_SCHEDULE C ON PRODUCT_MASTER.PROD_I_CODE=C.CS_I_CODE INNER JOIN PARTY_MASTER P ON C.CS_P_CODE=P.P_CODE WHERE  " + cond + "  C.ES_DELETE =0 AND P.ES_DELETE =0 AND (ITEM_MASTER.I_CM_COMP_ID = '" + Session["CompanyID"].ToString() + "') AND (ITEM_MASTER.ES_DELETE = 0) AND (ITEM_MASTER.I_CAT_CODE = '-2147483648') and PRODUCT_MASTER.ES_DELETE=0 and GROUP_MASTER.ES_DELETE=0 group by P.P_CODE,P.P_NAME,I_TARGET_WEIGHT,GP_NAME,I_INV_RATE,I_CODE ORDER BY P.P_NAME select P_CODE,P_NAME, sum(isnull(CS_SCHEDULE_QTY,0)) as CS_SCHEDULE_QTY,sum(isnull(PROD_FINISH_WT,0)) as PROD_FINISH_WT,sum(isnull(CPOD_RATE,0)) as CPOD_RATE from #Temp group by P_CODE,P_NAME ORDER BY P_NAME drop table #Temp";
                Query = "SELECT ITEM_MASTER.I_CODE,ITEM_MASTER.I_NAME,ITEM_MASTER.I_CODENO ,isnull((select SUM(ISNULL(CS_SCHEDULE_QTY,0)) FROM CUSTOMER_SCHEDULE where " + cond + " CUSTOMER_SCHEDULE.CS_I_CODE=I_CODE and CUSTOMER_SCHEDULE.ES_DELETE=0),0) as CS_SCHEDULE_QTY,isnull((isnull((select SUM(ISNULL(CS_SCHEDULE_QTY,0)) FROM CUSTOMER_SCHEDULE where " + cond + " CUSTOMER_SCHEDULE.CS_I_CODE=I_CODE AND CS_P_CODE=P_CODE and CUSTOMER_SCHEDULE.ES_DELETE=0),0)* ISNULL(I_TARGET_WEIGHT,0)),0)/1000 as PROD_FINISH_WT ,GROUP_MASTER.GP_NAME ,isnull((isnull((select SUM(ISNULL(CS_SCHEDULE_QTY,0)) FROM CUSTOMER_SCHEDULE where " + cond + " CUSTOMER_SCHEDULE.CS_I_CODE=I_CODE AND CS_P_CODE=P_CODE and CUSTOMER_SCHEDULE.ES_DELETE=0),0) * isnull(I_INV_RATE,0)),0)/100000 AS CPOD_RATE,P.P_CODE,P.P_NAME into #Temp  FROM ITEM_MASTER INNER JOIN PRODUCT_MASTER INNER JOIN GROUP_MASTER ON PRODUCT_MASTER.PROD_GP_CODE = GROUP_MASTER.GP_CODE ON ITEM_MASTER.I_CODE = PRODUCT_MASTER.PROD_I_CODE INNER JOIN CUSTOMER_SCHEDULE C ON PRODUCT_MASTER.PROD_I_CODE=C.CS_I_CODE inner join PARTY_MASTER P ON CS_P_CODE=P.P_CODE WHERE  " + cond + " C.ES_DELETE =0 AND P.ES_DELETE =0 AND (ITEM_MASTER.I_CM_COMP_ID = '" + Session["CompanyID"].ToString() + "') AND (ITEM_MASTER.ES_DELETE = 0) AND (ITEM_MASTER.I_CAT_CODE = '-2147483648') and PRODUCT_MASTER.ES_DELETE=0 and GROUP_MASTER.ES_DELETE=0  group by ITEM_MASTER.I_CODE,ITEM_MASTER.I_NAME,ITEM_MASTER.I_CODENO,I_TARGET_WEIGHT,GP_NAME,I_INV_RATE,P.P_CODE,P_NAME ORDER BY ITEM_MASTER.I_CODENO select P_CODE,P_NAME, sum(isnull(CS_SCHEDULE_QTY,0)) as CS_SCHEDULE_QTY,sum(isnull(PROD_FINISH_WT,0)) as PROD_FINISH_WT,sum(isnull(CPOD_RATE,0)) as CPOD_RATE from #Temp group by P_CODE,P_NAME ORDER BY P_NAME drop table #Temp";
                DataSet ds = new DataSet();
                DataTable dt = new DataTable();
                dt = CommonClasses.Execute(Query);
                if (dt.Rows.Count > 0)
                {
                    ReportDocument rptname = null;
                    rptname = new ReportDocument();

                    rptname.Load(Server.MapPath("~/PPC/Reports/rptSalesSummaryOwnerwise.rpt"));
                    rptname.FileName = Server.MapPath("~/PPC/Reports/rptSalesSummaryOwnerwise.rpt");
                    rptname.Refresh();
                    rptname.SetDataSource(dt);

                    rptname.SetParameterValue("txtCompName", Session["CompanyName"].ToString());
                    rptname.SetParameterValue("Title", Title);
                    rptname.SetParameterValue("txttype", 1);
                    CrystalReportViewer1.ReportSource = rptname;
                }
                else
                {
                    PanelMsg.Visible = true;
                    lblmsg.Text = "Record Not Found";
                    return;
                }
            }
            else
            {
                //Query = "SELECT PARTY_MASTER.P_NAME, sum(CUSTPO_DETAIL.CPOD_AMT) as CPOD_AMT,'' as TONNAGE,'' as REMARK FROM PARTY_MASTER INNER JOIN CUSTPO_MASTER INNER JOIN CUSTPO_DETAIL ON CUSTPO_MASTER.CPOM_CODE = CUSTPO_DETAIL.CPOD_CPOM_CODE ON PARTY_MASTER.P_CODE = CUSTPO_MASTER.CPOM_P_CODE WHERE  (CUSTPO_MASTER.ES_DELETE = 0) " + cond + " and PARTY_MASTER.ES_DELETE=0 group by P_NAME order by P_NAME";
                //Query = "SELECT sum(INVOICE_MASTER.INM_NET_AMT) as CPOD_AMT, PARTY_MASTER.P_CODE, PARTY_MASTER.P_NAME FROM GROUP_MASTER INNER JOIN PRODUCT_MASTER ON GROUP_MASTER.GP_CODE = PRODUCT_MASTER.PROD_GP_CODE INNER JOIN CUSTPO_DETAIL INNER JOIN CUSTPO_MASTER ON CUSTPO_DETAIL.CPOD_CPOM_CODE = CUSTPO_MASTER.CPOM_CODE INNER JOIN INVOICE_MASTER INNER JOIN INVOICE_DETAIL ON INVOICE_MASTER.INM_CODE = INVOICE_DETAIL.IND_INM_CODE ON CUSTPO_MASTER.CPOM_CODE = INVOICE_DETAIL.IND_CPOM_CODE AND CUSTPO_DETAIL.CPOD_I_CODE = INVOICE_DETAIL.IND_I_CODE INNER JOIN ITEM_MASTER ON INVOICE_DETAIL.IND_I_CODE = ITEM_MASTER.I_CODE INNER JOIN PARTY_MASTER ON INVOICE_MASTER.INM_P_CODE = PARTY_MASTER.P_CODE ON PRODUCT_MASTER.PROD_I_CODE = CUSTPO_DETAIL.CPOD_I_CODE WHERE (INVOICE_MASTER.ES_DELETE = 0) " + cond + " AND (INVOICE_MASTER.INM_TYPE = 'TAXINV') AND (INVOICE_MASTER.INM_IS_SUPPLIMENT = 0) group by PARTY_MASTER.P_CODE, PARTY_MASTER.P_NAME";
                //Query = "SELECT P.P_CODE,P.P_NAME,ISNULL(SUM(CS_SCHEDULE_QTY),0) as CS_SCHEDULE_QTY, ISNULL(CUSTPO_DETAIL.CPOD_RATE,0) AS CPOD_RATE,ISNULL(I_TARGET_WEIGHT,0) as PROD_FINISH_WT,GP_OWNER into #Temp FROM CUSTPO_MASTER INNER JOIN ITEM_MASTER INNER JOIN PRODUCT_MASTER INNER JOIN GROUP_MASTER ON PRODUCT_MASTER.PROD_GP_CODE = GROUP_MASTER.GP_CODE ON ITEM_MASTER.I_CODE = PRODUCT_MASTER.PROD_I_CODE INNER JOIN CUSTPO_DETAIL ON ITEM_MASTER.I_CODE = CUSTPO_DETAIL.CPOD_I_CODE ON CUSTPO_MASTER.CPOM_CODE = CUSTPO_DETAIL.CPOD_CPOM_CODE INNER JOIN CUSTOMER_SCHEDULE C ON PRODUCT_MASTER.PROD_I_CODE=C.CS_I_CODE inner join PARTY_MASTER P ON CPOM_P_CODE=P.P_CODE WHERE " + cond + " C.ES_DELETE =0 AND P.ES_DELETE =0 AND (CUSTPO_MASTER.ES_DELETE = 0) AND (ITEM_MASTER.I_CM_COMP_ID = '" + Session["CompanyID"].ToString() + "') AND (ITEM_MASTER.ES_DELETE = 0) AND (ITEM_MASTER.I_CAT_CODE = '-2147483648') and PRODUCT_MASTER.ES_DELETE=0 and GROUP_MASTER.ES_DELETE=0 GROUP BY P.P_CODE,P.P_NAME,CPOD_RATE,I_TARGET_WEIGHT,GP_OWNER select SUM(isnull(CS_SCHEDULE_QTY,0)) as CS_SCHEDULE_QTY ,sum(ISNULL(CPOD_RATE,0)) AS CPOD_RATE,sum(ISNULL(PROD_FINISH_WT,0)) as PROD_FINISH_WT ,GP_OWNER,UM_NAME as P_NAME from #Temp inner join USER_MASTER  on GP_OWNER=UM_CODE AND USER_MASTER.ES_DELETE=0 group by GP_OWNER,UM_NAME DROP TABLE #Temp";
                //Query = "SELECT P.P_CODE,P.P_NAME,(sum(ISNULL(CS_SCHEDULE_QTY,0)) * ISNULL(I_INV_RATE,0)) as CS_SCHEDULE_QTY,(sum(ISNULL(CS_SCHEDULE_QTY,0))* ISNULL(I_TARGET_WEIGHT,0)) as PROD_FINISH_WT ,I_INV_RATE AS CPOD_RATE,GP_OWNER into #Temp FROM ITEM_MASTER INNER JOIN PRODUCT_MASTER INNER JOIN GROUP_MASTER ON PRODUCT_MASTER.PROD_GP_CODE = GROUP_MASTER.GP_CODE ON ITEM_MASTER.I_CODE = PRODUCT_MASTER.PROD_I_CODE INNER JOIN CUSTOMER_SCHEDULE C ON PRODUCT_MASTER.PROD_I_CODE=C.CS_I_CODE INNER JOIN PARTY_MASTER P ON C.CS_P_CODE=P.P_CODE WHERE " + cond + " C.ES_DELETE =0 AND P.ES_DELETE =0 AND (ITEM_MASTER.I_CM_COMP_ID = '" + Session["CompanyID"].ToString() + "') AND (ITEM_MASTER.ES_DELETE = 0) AND (ITEM_MASTER.I_CAT_CODE = '-2147483648') and PRODUCT_MASTER.ES_DELETE=0 and GROUP_MASTER.ES_DELETE=0 group by P.P_CODE,P.P_NAME,I_TARGET_WEIGHT,GP_NAME,I_INV_RATE,GP_OWNER ORDER BY P.P_NAME  select SUM(isnull(CS_SCHEDULE_QTY,0)) as CS_SCHEDULE_QTY ,sum(ISNULL(CPOD_RATE,0)) AS CPOD_RATE,sum(ISNULL(PROD_FINISH_WT,0)) as PROD_FINISH_WT ,GP_OWNER,UM_NAME as P_NAME from #Temp inner join USER_MASTER  on GP_OWNER=UM_CODE AND USER_MASTER.ES_DELETE=0 group by GP_OWNER,UM_NAME DROP TABLE #Temp";
                //Query = "SELECT P_CODE,P_NAME,I_CODENO,GP_OWNER,isnull((select SUM(ISNULL(CS_SCHEDULE_QTY,0)) FROM CUSTOMER_SCHEDULE where " + cond + " CUSTOMER_SCHEDULE.CS_I_CODE=I_CODE and CUSTOMER_SCHEDULE.ES_DELETE=0 ),0) as CS_SCHEDULE_QTY,isnull((isnull((select SUM(ISNULL(CS_SCHEDULE_QTY,0)) FROM CUSTOMER_SCHEDULE where " + cond + " CUSTOMER_SCHEDULE.CS_I_CODE=I_CODE and CUSTOMER_SCHEDULE.ES_DELETE=0),0)  * ISNULL(I_TARGET_WEIGHT,0)),0)/1000 as PROD_FINISH_WT ,GROUP_MASTER.GP_NAME ,isnull((isnull((select SUM(ISNULL(CS_SCHEDULE_QTY,0)) FROM CUSTOMER_SCHEDULE where " + cond + " CUSTOMER_SCHEDULE.CS_I_CODE=I_CODE and CUSTOMER_SCHEDULE.ES_DELETE=0),0)* isnull(I_INV_RATE,0)),0)/100000 AS CPOD_RATE into #Temp FROM ITEM_MASTER INNER JOIN PRODUCT_MASTER INNER JOIN GROUP_MASTER ON PRODUCT_MASTER.PROD_GP_CODE = GROUP_MASTER.GP_CODE ON ITEM_MASTER.I_CODE = PRODUCT_MASTER.PROD_I_CODE INNER JOIN CUSTOMER_SCHEDULE C ON PRODUCT_MASTER.PROD_I_CODE=C.CS_I_CODE inner join PARTY_MASTER P ON CS_P_CODE=P.P_CODE  WHERE  " + cond + " C.ES_DELETE =0 AND P.ES_DELETE =0 AND (ITEM_MASTER.I_CM_COMP_ID = '" + Session["CompanyID"].ToString() + "') AND (ITEM_MASTER.ES_DELETE = 0) AND (ITEM_MASTER.I_CAT_CODE = '-2147483648') and PRODUCT_MASTER.ES_DELETE=0 and GROUP_MASTER.ES_DELETE=0 group by ITEM_MASTER.I_CODE,I_TARGET_WEIGHT,GP_NAME,I_INV_RATE,P_CODE,P_NAME,I_CODENO,GP_OWNER ORDER BY P_NAME select GP_OWNER,UM_NAME,SUM(CS_SCHEDULE_QTY) AS CS_SCHEDULE_QTY,SUM(PROD_FINISH_WT) AS PROD_FINISH_WT,SUM(CPOD_RATE) AS CPOD_RATE,UM_NAME as P_NAME from #Temp inner join USER_MASTER  on GP_OWNER=UM_CODE AND USER_MASTER.ES_DELETE=0 group by GP_OWNER,UM_NAME  DROP TABLE #Temp";
                //Query = "SELECT P.P_CODE,P.P_NAME,sum(ISNULL(CS_SCHEDULE_QTY,0)) as CS_SCHEDULE_QTY,sum(ISNULL(CS_SCHEDULE_QTY,0)) as PROD_FINISH_WT ,I_INV_RATE AS CPOD_RATE,GP_OWNER into #Temp FROM ITEM_MASTER INNER JOIN PRODUCT_MASTER INNER JOIN GROUP_MASTER ON PRODUCT_MASTER.PROD_GP_CODE = GROUP_MASTER.GP_CODE ON ITEM_MASTER.I_CODE = PRODUCT_MASTER.PROD_I_CODE INNER JOIN CUSTOMER_SCHEDULE C ON PRODUCT_MASTER.PROD_I_CODE=C.CS_I_CODE INNER JOIN PARTY_MASTER P ON C.CS_P_CODE=P.P_CODE WHERE " + cond + " C.ES_DELETE =0 AND P.ES_DELETE =0 AND (ITEM_MASTER.I_CM_COMP_ID = '" + Session["CompanyID"].ToString() + "') AND (ITEM_MASTER.ES_DELETE = 0) AND (ITEM_MASTER.I_CAT_CODE = '-2147483648') and PRODUCT_MASTER.ES_DELETE=0 and GROUP_MASTER.ES_DELETE=0 group by P.P_CODE,P.P_NAME,I_TARGET_WEIGHT,GP_NAME,I_INV_RATE,GP_OWNER ORDER BY P.P_NAME  select SUM(isnull(CS_SCHEDULE_QTY,0)) as CS_SCHEDULE_QTY ,sum(ISNULL(CPOD_RATE,0)) AS CPOD_RATE,sum(ISNULL(PROD_FINISH_WT,0)) as PROD_FINISH_WT ,GP_OWNER,UM_NAME as P_NAME from #Temp inner join USER_MASTER  on GP_OWNER=UM_CODE AND USER_MASTER.ES_DELETE=0 group by GP_OWNER,UM_NAME DROP TABLE #Temp";
                Query = "SELECT ITEM_MASTER.I_CODE,ITEM_MASTER.I_NAME,ITEM_MASTER.I_CODENO ,isnull((select SUM(ISNULL(CS_SCHEDULE_QTY,0)) FROM CUSTOMER_SCHEDULE where " + cond + " CUSTOMER_SCHEDULE.CS_I_CODE=I_CODE and CUSTOMER_SCHEDULE.ES_DELETE=0),0) as CS_SCHEDULE_QTY,isnull((isnull((select SUM(ISNULL(CS_SCHEDULE_QTY,0)) FROM CUSTOMER_SCHEDULE where " + cond + " CUSTOMER_SCHEDULE.CS_I_CODE=I_CODE AND CS_P_CODE=P_CODE and CUSTOMER_SCHEDULE.ES_DELETE=0),0)* ISNULL(I_TARGET_WEIGHT,0)),0)/1000 as PROD_FINISH_WT ,GROUP_MASTER.GP_NAME ,isnull((isnull((select SUM(ISNULL(CS_SCHEDULE_QTY,0)) FROM CUSTOMER_SCHEDULE where " + cond + " CUSTOMER_SCHEDULE.CS_I_CODE=I_CODE AND CS_P_CODE=P_CODE and CUSTOMER_SCHEDULE.ES_DELETE=0),0) * isnull(I_INV_RATE,0)),0)/100000 AS CPOD_RATE,P.P_CODE,P.P_NAME,GP_OWNER into #Temp  FROM ITEM_MASTER INNER JOIN PRODUCT_MASTER INNER JOIN GROUP_MASTER ON PRODUCT_MASTER.PROD_GP_CODE = GROUP_MASTER.GP_CODE ON ITEM_MASTER.I_CODE = PRODUCT_MASTER.PROD_I_CODE INNER JOIN CUSTOMER_SCHEDULE C ON PRODUCT_MASTER.PROD_I_CODE=C.CS_I_CODE inner join PARTY_MASTER P ON CS_P_CODE=P.P_CODE WHERE " + cond + " C.ES_DELETE =0 AND P.ES_DELETE =0 AND (ITEM_MASTER.I_CM_COMP_ID = '" + Session["CompanyID"].ToString() + "') AND (ITEM_MASTER.ES_DELETE = 0) AND (ITEM_MASTER.I_CAT_CODE = '-2147483648') and PRODUCT_MASTER.ES_DELETE=0 and GROUP_MASTER.ES_DELETE=0  group by ITEM_MASTER.I_CODE,ITEM_MASTER.I_NAME,ITEM_MASTER.I_CODENO,I_TARGET_WEIGHT,GP_NAME,I_INV_RATE,P.P_CODE,P_NAME,GP_OWNER,GP_CODE ORDER BY ITEM_MASTER.I_CODENO select GP_OWNER,UM_NAME, sum(isnull(CS_SCHEDULE_QTY,0)) as CS_SCHEDULE_QTY,sum(isnull(PROD_FINISH_WT,0)) as PROD_FINISH_WT,sum(isnull(CPOD_RATE,0)) as CPOD_RATE,UM_NAME as P_NAME from #Temp inner join USER_MASTER  on GP_OWNER=UM_CODE AND USER_MASTER.ES_DELETE=0 group by GP_OWNER,UM_NAME ORDER BY UM_NAME drop table #Temp";
                DataSet ds = new DataSet();
                DataTable dt = new DataTable();
                dt = CommonClasses.Execute(Query);
                if (dt.Rows.Count > 0)
                {
                    ReportDocument rptname = null;
                    rptname = new ReportDocument();

                    rptname.Load(Server.MapPath("~/PPC/Reports/rptSalesSummaryOwnerwise.rpt"));
                    rptname.FileName = Server.MapPath("~/PPC/Reports/rptSalesSummaryOwnerwise.rpt");
                    rptname.Refresh();
                    rptname.SetDataSource(dt);

                    rptname.SetParameterValue("txtCompName", Session["CompanyName"].ToString());
                    rptname.SetParameterValue("Title", Title);
                    rptname.SetParameterValue("txttype", 0);
                    CrystalReportViewer1.ReportSource = rptname;
                }
                else
                {
                    PanelMsg.Visible = true;
                    lblmsg.Text = "Record Not Found";
                    return;
                }
            }
        }
        catch (Exception Ex)
        {
        }
    }
    #endregion

    #region ShowMessage
    public bool ShowMessage(string DiveName, string Message, string MessageType)
    {
        try
        {
            if ((!ClientScript.IsStartupScriptRegistered("regMostrarMensagem")))
            {
                Page.ClientScript.RegisterStartupScript(this.GetType(), "regMostrarMensagem", "MostrarMensagem('" + DiveName + "', '" + Message + "', '" + MessageType + "');", true);
            }
            return true;
        }
        catch (Exception Ex)
        {
            CommonClasses.SendError("Sales Order Rport", "ShowMessage", Ex.Message);
            return false;
        }
    }
    #endregion

    #region btnCancel_Click
    protected void btnCancel_Click(object sender, EventArgs e)
    {
        try
        {
            if (type == "Cust")
            {
                Response.Redirect("../../ReportForms/View/ViewSaleSummaryCustomerwise.aspx", false);
            }
            else
            {
                Response.Redirect("../../ReportForms/View/ViewSaleSummaryOwnerwise.aspx", false);
            }
        }
        catch (Exception Ex)
        {
            CommonClasses.SendError("Sales Order Report", "btnCancel_Click", Ex.Message);
        }
    }
    #endregion
}