using System;
using System.Data;
using CrystalDecisions.CrystalReports.Engine;
using System.Web.UI.HtmlControls;
using ZXing;
using System.IO;
using System.Drawing;
using System.Drawing.Imaging;

public partial class RoportForms_ADD_LabourChargeInvoicePrint : System.Web.UI.Page
{
    DatabaseAccessLayer DL_DBAccess = null;
    string invoice_code = "";
    string reportType = "";
    string type = "";
    string title = "";
    string Cond = "";
    string chkPrint1 = "";
    string rptType = "";
    string toNo = "";
    string ptype = "";
    ReportDocument rptname = null;
    protected void Page_Load(object sender, EventArgs e)
    {
        HtmlGenericControl home = (HtmlGenericControl)this.Page.Master.FindControl("Menus").FindControl("Sale");
        home.Attributes["class"] = "active";
        HtmlGenericControl home1 = (HtmlGenericControl)this.Page.Master.FindControl("Menus").FindControl("Sale1MV");
        home1.Attributes["class"] = "active";
    }

    protected void Page_Init(object sender, EventArgs e)
    {
        string FrmDelieveryChallanFlag = "";
        string Title = Request.QueryString[0];
        Cond = Request.QueryString[1];
        chkPrint1 = Convert.ToInt32(Request.QueryString[2]).ToString();
        invoice_code = Request.QueryString[3];
        reportType = Request.QueryString[4];
        //}
        if (reportType == "Mult")
        {
            toNo = Request.QueryString[5];
            ptype = Request.QueryString[6];
            rptType = Request.QueryString[6];
        }
        else
        {
            rptType = Request.QueryString[5];
            ptype = Request.QueryString[5];
            FrmDelieveryChallanFlag = Request.QueryString[6];
        }

        //FrmDelieveryChallanFlag = Request.QueryString[7];
        //invoice_code = Request.QueryString[0];
        //reportType = Request.QueryString[1];
        //string ptype = Request.QueryString[2];
        GenerateReport(invoice_code, ptype, FrmDelieveryChallanFlag);
    }

    #region GenerateReport
    private void GenerateReport(string code, string type, string FrmDelieveryChallanFlag)
    {
        DL_DBAccess = new DatabaseAccessLayer();
        //DataTable dtfinal = CommonClasses.Execute("select EM_CODE ,EM_NAME ,BM_NAME,CONVERT(VARCHAR(11),EM_JOINDATE,113) as EM_JOINDATE,CONVERT(VARCHAR(11),FS_LEAVE_DATE,113) as FS_LEAVE_DATE,CONVERT(VARCHAR(11),FS_RESIGN_DATE,113) as FS_RESIGN_DATE,DS_NAME,FS_LAST_SAL,FS_BONUS_AMT,FS_LEAVE_AMT,FS_LTA_AMT,FS_ADV_AMT,FS_LOAN_AMT,FS_NOTICE_AMT,FS_FINAL_AMT,FS_PAYABLE_LEAVES as LeaveDay,FS_NOTICE_DAYS as NoticeDay from HR_FINAL_SETTLEMENT,HR_EMPLOYEE_MASTER,HR_DESINGNATION_MASTER,CM_BRANCH_MASTER where EM_CODE=FS_EM_CODE and BM_CODE=EM_BM_CODE and EM_DM_CODE=DS_CODE and FS_CODE=" + fsCode + " and FS_DELETE_FLAG=0 and FS_CM_COMP_ID=" + Session["CompanyId"].ToString() + ""); 
        try
        {
            DataTable dtfinal = new DataTable();
            if (reportType == "Single")
            {
                if (FrmDelieveryChallanFlag.Equals("1"))
                {
                    //dtfinal = CommonClasses.Execute("SELECT DISTINCT ITEM_MASTER.I_CODE, PARTY_MASTER.P_CODE, EXCISE_TARIFF_MASTER.E_TARIFF_NO, PARTY_MASTER.P_NAME, PARTY_MASTER.P_ADD1, PARTY_MASTER.P_VEND_CODE, PARTY_MASTER.P_CST, PARTY_MASTER.P_VAT, PARTY_MASTER.P_ECC_NO, LIM_NO as INM_TNO, LIM_NO as INM_NO, INVOICE_MASTER.INM_DATE, INVOICE_MASTER.INM_TRANSPORT, INVOICE_MASTER.INM_VEH_NO, INVOICE_MASTER.INM_LR_NO, INVOICE_MASTER.INM_LR_DATE, ITEM_MASTER.I_NAME, ITEM_MASTER.I_CODENO AS CPOD_CUST_I_CODE, INVOICE_DETAIL.IND_PACK_DESC AS CPOD_CUST_I_NAME, CUSTPO_MASTER.CPOM_PONO, SALES_TAX_MASTER.ST_TAX_NAME, CUSTPO_MASTER.CPOM_PO_DATE AS CPOM_DATE, INVOICE_DETAIL.IND_SUBHEADING, INVOICE_DETAIL.IND_BACHNO, INVOICE_DETAIL.IND_NO_PACK, CAST(ISNULL(INVOICE_DETAIL.IND_PAK_QTY, 0) AS numeric(20, 3)) AS IND_PAK_QTY, CAST(ISNULL(INVOICE_DETAIL.IND_INQTY, 0) AS numeric(20, 3)) AS IND_INQTY, CAST(ISNULL(INVOICE_DETAIL.IND_RATE, 0) AS numeric(20, 2)) AS IND_RATE, CAST(ISNULL(INVOICE_DETAIL.IND_AMT, 0) AS numeric(20, 2)) AS IND_AMT, CAST(ISNULL(INVOICE_MASTER.INM_NET_AMT, 0) AS numeric(20, 2)) AS INM_NET_AMT, CAST(ISNULL(INVOICE_MASTER.INM_DISC, 0) AS numeric(20, 2)) AS INM_DISC, CAST(ISNULL(INVOICE_MASTER.INM_DISC_AMT, 0) AS numeric(20, 2)) AS INM_DISC_AMT, CAST(ISNULL(INVOICE_MASTER.INM_PACK_AMT, 0) AS numeric(20, 2)) AS INM_PACK_AMT, CAST(ISNULL(INVOICE_MASTER.INM_ACCESSIBLE_AMT, 0) AS numeric(20, 2)) AS INM_ACCESSIBLE_AMT, CAST(ISNULL(INVOICE_MASTER.INM_BEXCISE, 0) AS numeric(20, 2)) AS INM_BEXCISE, CAST(ISNULL(INVOICE_MASTER.INM_BE_AMT, 0) AS numeric(20, 2)) AS INM_BE_AMT, CAST(ISNULL(INVOICE_MASTER.INM_EDUC_CESS, 0) AS numeric(20, 2)) AS INM_EDUC_CESS, CAST(ISNULL(INVOICE_MASTER.INM_EDUC_AMT, 0) AS numeric(20, 2)) AS INM_EDUC_AMT, CAST(ISNULL(INVOICE_MASTER.INM_H_EDUC_CESS, 0) AS numeric(20, 2)) AS INM_H_EDUC_CESS, CAST(ISNULL(INVOICE_MASTER.INM_H_EDUC_AMT, 0) AS numeric(20, 2)) AS INM_H_EDUC_AMT, CAST(ISNULL(INVOICE_MASTER.INM_TAXABLE_AMT, 0) AS numeric(20, 2)) AS INM_TAXABLE_AMT, CAST(ISNULL(INVOICE_MASTER.INM_S_TAX, 0) AS numeric(20, 2)) AS INM_S_TAX, CAST(ISNULL(INVOICE_MASTER.INM_S_TAX_AMT, 0) AS numeric(20, 2)) AS INM_S_TAX_AMT, CAST(ISNULL(INVOICE_MASTER.INM_OTHER_AMT, 0) AS numeric(20, 2)) AS INM_OTHER_AMT, CAST(ISNULL(INVOICE_MASTER.INM_FREIGHT, 0) AS numeric(20, 2)) AS INM_FREIGHT, CAST(ISNULL(INVOICE_MASTER.INM_INSURANCE, 0) AS numeric(20, 2)) AS INM_INSURANCE, CAST(ISNULL(INVOICE_MASTER.INM_TRANS_AMT, 0) AS numeric(20, 2)) AS INM_TRANS_AMT, CAST(ISNULL(INVOICE_MASTER.INM_OCTRI_AMT, 0) AS numeric(20, 2)) AS INM_OCTRI_AMT, CAST(ISNULL(INVOICE_MASTER.INM_ROUNDING_AMT, 0) AS numeric(20, 2)) AS INM_ROUNDING_AMT, CAST(ISNULL(INVOICE_MASTER.INM_G_AMT, 0) AS numeric(20, 2)) AS INM_G_AMT, CAST(ISNULL(INVOICE_MASTER.INM_TAX_TCS_AMT, 0) AS numeric(20, 2)) AS INM_TAX_TCS_AMT, INVOICE_MASTER.INM_ISSUE_DATE, INVOICE_MASTER.INM_REMOVAL_DATE, INVOICE_MASTER.INM_ISSU_TIME, INVOICE_MASTER.INM_REMOVEL_TIME, EXCISE_TARIFF_MASTER.E_COMMODITY, ITEM_UNIT_MASTER.I_UOM_NAME, INVOICE_MASTER.INM_TAX_TCS, ISNULL(INVOICE_DETAIL.IND_AMORTAMT, 0) AS IND_AMORTAMT, ISNULL(INVOICE_DETAIL.IND_AMORTRATE, 0) AS IND_AMORTRATE FROM LABOR_INVOICE_MASTER INNER JOIN LABOR_INVOICE_DETAIL ON LABOR_INVOICE_MASTER.LIM_CODE = LABOR_INVOICE_DETAIL.LID_LIM_CODE INNER JOIN SALES_TAX_MASTER INNER JOIN INVOICE_DETAIL INNER JOIN INVOICE_MASTER ON INVOICE_DETAIL.IND_INM_CODE = INVOICE_MASTER.INM_CODE INNER JOIN PARTY_MASTER ON INVOICE_MASTER.INM_P_CODE = PARTY_MASTER.P_CODE INNER JOIN CUSTPO_MASTER INNER JOIN CUSTPO_DETAIL ON CUSTPO_MASTER.CPOM_CODE = CUSTPO_DETAIL.CPOD_CPOM_CODE ON INVOICE_MASTER.INM_P_CODE = CUSTPO_MASTER.CPOM_P_CODE AND INVOICE_DETAIL.IND_CPOM_CODE = CUSTPO_MASTER.CPOM_CODE AND INVOICE_DETAIL.IND_I_CODE = CUSTPO_DETAIL.CPOD_I_CODE AND INVOICE_DETAIL.IND_I_CODE = CUSTPO_DETAIL.CPOD_I_CODE INNER JOIN ITEM_MASTER ON INVOICE_DETAIL.IND_I_CODE = ITEM_MASTER.I_CODE INNER JOIN EXCISE_TARIFF_MASTER ON ITEM_MASTER.I_E_CODE = EXCISE_TARIFF_MASTER.E_CODE ON SALES_TAX_MASTER.ST_CODE = CUSTPO_DETAIL.CPOD_ST_CODE INNER JOIN ITEM_UNIT_MASTER ON ITEM_MASTER.I_UOM_CODE = ITEM_UNIT_MASTER.I_UOM_CODE ON LABOR_INVOICE_DETAIL.LID_INM_CODE = INVOICE_MASTER.INM_CODE AND LABOR_INVOICE_DETAIL.LID_I_CODE = INVOICE_DETAIL.IND_I_CODE WHERE (INVOICE_MASTER.INM_TYPE = 'OutJWINM') AND (INVOICE_MASTER.INM_CM_CODE = '" + Convert.ToInt32(Session["CompanyCode"]) + "') and LABOR_INVOICE_MASTER.ES_DELETE=0 AND LIM_CODE=" + code + "");
                    //dtfinal = CommonClasses.Execute("SELECT DISTINCT ITEM_MASTER.I_CODE,PARTY_MASTER.P_CODE,P_GST_NO,EXCISE_TARIFF_MASTER.E_TARIFF_NO, PARTY_MASTER.P_NAME, PARTY_MASTER.P_ADD1, PARTY_MASTER.P_VEND_CODE, PARTY_MASTER.P_CST, PARTY_MASTER.P_VAT, PARTY_MASTER.P_ECC_NO,  'JPDC'+CONVERT(varchar, LIM_NO)  as INM_TNO, LIM_NO as INM_NO, INVOICE_MASTER.INM_DATE, INVOICE_MASTER.INM_TRANSPORT, INVOICE_MASTER.INM_VEH_NO, INVOICE_MASTER.INM_LR_NO, INVOICE_MASTER.INM_LR_DATE, ITEM_MASTER.I_NAME, ITEM_MASTER.I_CODENO AS CPOD_CUST_I_CODE, INVOICE_DETAIL.IND_PACK_DESC AS CPOD_CUST_I_NAME, CUSTPO_MASTER.CPOM_PONO, SALES_TAX_MASTER.ST_TAX_NAME, CUSTPO_MASTER.CPOM_PO_DATE AS CPOM_DATE, INVOICE_DETAIL.IND_SUBHEADING, INVOICE_DETAIL.IND_BACHNO, INVOICE_DETAIL.IND_NO_PACK, CAST(ISNULL(INVOICE_DETAIL.IND_PAK_QTY, 0) AS numeric(20, 3)) AS IND_PAK_QTY, CAST(ISNULL(INVOICE_DETAIL.IND_INQTY, 0) AS numeric(20, 3)) AS IND_INQTY, CAST(ISNULL(INVOICE_DETAIL.IND_RATE, 0) AS numeric(20, 2)) AS IND_RATE, CAST(ISNULL(INVOICE_DETAIL.IND_AMT, 0) AS numeric(20, 2)) AS IND_AMT, CAST(ISNULL(INVOICE_MASTER.INM_NET_AMT, 0) AS numeric(20, 2)) AS INM_NET_AMT, CAST(ISNULL(INVOICE_MASTER.INM_DISC, 0) AS numeric(20, 2)) AS INM_DISC, CAST(ISNULL(INVOICE_MASTER.INM_DISC_AMT, 0) AS numeric(20, 2)) AS INM_DISC_AMT, CAST(ISNULL(INVOICE_MASTER.INM_PACK_AMT, 0) AS numeric(20, 2)) AS INM_PACK_AMT, CAST(ISNULL(INVOICE_MASTER.INM_ACCESSIBLE_AMT, 0) AS numeric(20, 2)) AS INM_ACCESSIBLE_AMT, CAST(ISNULL(INVOICE_MASTER.INM_BEXCISE, 0) AS numeric(20, 2)) AS INM_BEXCISE, CAST(ISNULL(INVOICE_MASTER.INM_BE_AMT, 0) AS numeric(20, 2)) AS INM_BE_AMT, CAST(ISNULL(INVOICE_MASTER.INM_EDUC_CESS, 0) AS numeric(20, 2)) AS INM_EDUC_CESS, CAST(ISNULL(INVOICE_MASTER.INM_EDUC_AMT, 0) AS numeric(20, 2)) AS INM_EDUC_AMT, CAST(ISNULL(INVOICE_MASTER.INM_H_EDUC_CESS, 0) AS numeric(20, 2)) AS INM_H_EDUC_CESS, CAST(ISNULL(INVOICE_MASTER.INM_H_EDUC_AMT, 0) AS numeric(20, 2)) AS INM_H_EDUC_AMT, CAST(ISNULL(INVOICE_MASTER.INM_TAXABLE_AMT, 0) AS numeric(20, 2)) AS INM_TAXABLE_AMT, CAST(ISNULL(INVOICE_MASTER.INM_S_TAX, 0) AS numeric(20, 2)) AS INM_S_TAX, CAST(ISNULL(INVOICE_MASTER.INM_S_TAX_AMT, 0) AS numeric(20, 2)) AS INM_S_TAX_AMT, CAST(ISNULL(INVOICE_MASTER.INM_OTHER_AMT, 0) AS numeric(20, 2)) AS INM_OTHER_AMT, CAST(ISNULL(INVOICE_MASTER.INM_FREIGHT, 0) AS numeric(20, 2)) AS INM_FREIGHT, CAST(ISNULL(INVOICE_MASTER.INM_INSURANCE, 0) AS numeric(20, 2)) AS INM_INSURANCE, CAST(ISNULL(INVOICE_MASTER.INM_TRANS_AMT, 0) AS numeric(20, 2)) AS INM_TRANS_AMT, CAST(ISNULL(INVOICE_MASTER.INM_OCTRI_AMT, 0) AS numeric(20, 2)) AS INM_OCTRI_AMT, CAST(ISNULL(INVOICE_MASTER.INM_ROUNDING_AMT, 0) AS numeric(20, 2)) AS INM_ROUNDING_AMT, CAST(ISNULL(INVOICE_MASTER.INM_G_AMT, 0) AS numeric(20, 2)) AS INM_G_AMT, CAST(ISNULL(INVOICE_MASTER.INM_TAX_TCS_AMT, 0) AS numeric(20, 2)) AS INM_TAX_TCS_AMT, INVOICE_MASTER.INM_ISSUE_DATE, INVOICE_MASTER.INM_REMOVAL_DATE, INVOICE_MASTER.INM_ISSU_TIME, INVOICE_MASTER.INM_REMOVEL_TIME, EXCISE_TARIFF_MASTER.E_COMMODITY, ITEM_UNIT_MASTER.I_UOM_NAME, INVOICE_MASTER.INM_TAX_TCS, ISNULL(INVOICE_DETAIL.IND_AMORTAMT, 0) AS IND_AMORTAMT, ISNULL(INVOICE_DETAIL.IND_AMORTRATE, 0) AS IND_AMORTRATE,ISNULL((SELECT DISTINCT (BD_VQTY+BD_SCRAPQTY) FROM BOM_MASTER,BOM_DETAIL WHERE BOM_MASTER.ES_DELETE=0 AND BOM_DETAIL.ES_DELETE=0 AND BOM_MASTER.BM_CODE=BOM_DETAIL.BD_BM_CODE AND BM_I_CODE=I_CODE),0) AS BD_QTY,ISNULL((SELECT TOP 1 ABS(CL_CQTY) FROM CHALLAN_STOCK_LEDGER where CL_DOC_ID=INM_CODE AND CL_ASSY_CODE=IND_I_CODE),0) AS CH_QTY,IND_EX_AMT as IND_EX_AMT,IND_E_CESS_AMT as IND_E_CESS_AMT,IND_SH_CESS_AMT as IND_SH_CESS_AMT into #temp FROM LABOR_INVOICE_MASTER INNER JOIN LABOR_INVOICE_DETAIL ON LABOR_INVOICE_MASTER.LIM_CODE = LABOR_INVOICE_DETAIL.LID_LIM_CODE INNER JOIN SALES_TAX_MASTER INNER JOIN INVOICE_DETAIL INNER JOIN INVOICE_MASTER ON INVOICE_DETAIL.IND_INM_CODE = INVOICE_MASTER.INM_CODE INNER JOIN PARTY_MASTER ON INVOICE_MASTER.INM_P_CODE = PARTY_MASTER.P_CODE INNER JOIN CUSTPO_MASTER INNER JOIN CUSTPO_DETAIL ON CUSTPO_MASTER.CPOM_CODE = CUSTPO_DETAIL.CPOD_CPOM_CODE ON INVOICE_MASTER.INM_P_CODE = CUSTPO_MASTER.CPOM_P_CODE AND INVOICE_DETAIL.IND_CPOM_CODE = CUSTPO_MASTER.CPOM_CODE AND INVOICE_DETAIL.IND_I_CODE = CUSTPO_DETAIL.CPOD_I_CODE AND INVOICE_DETAIL.IND_I_CODE = CUSTPO_DETAIL.CPOD_I_CODE INNER JOIN ITEM_MASTER ON INVOICE_DETAIL.IND_I_CODE = ITEM_MASTER.I_CODE INNER JOIN EXCISE_TARIFF_MASTER ON ITEM_MASTER.I_E_CODE = EXCISE_TARIFF_MASTER.E_CODE ON SALES_TAX_MASTER.ST_CODE = CUSTPO_DETAIL.CPOD_ST_CODE INNER JOIN ITEM_UNIT_MASTER ON ITEM_MASTER.I_UOM_CODE = ITEM_UNIT_MASTER.I_UOM_CODE ON LABOR_INVOICE_DETAIL.LID_INM_CODE = INVOICE_MASTER.INM_CODE AND LABOR_INVOICE_DETAIL.LID_I_CODE = INVOICE_DETAIL.IND_I_CODE WHERE (INVOICE_MASTER.INM_TYPE = 'OutJWINM') AND (INVOICE_MASTER.INM_CM_CODE = '" + Convert.ToInt32(Session["CompanyCode"]) + "') and LABOR_INVOICE_MASTER.ES_DELETE=0 AND LIM_CODE=" + code + " SELECT I_CODE,P_CODE,P_GST_NO,E_TARIFF_NO,P_NAME,P_ADD1,P_VEND_CODE,P_CST,P_VAT,P_ECC_NO,INM_TNO,INM_NO,INM_DATE,INM_TRANSPORT,INM_VEH_NO,INM_LR_NO,INM_LR_DATE,I_NAME,CPOD_CUST_I_CODE,CPOD_CUST_I_NAME,CPOM_PONO,ST_TAX_NAME,CPOM_DATE,IND_SUBHEADING,IND_BACHNO,IND_NO_PACK,IND_PAK_QTY,SUM(IND_INQTY) As IND_INQTY ,IND_RATE,SUM(IND_AMT) As IND_AMT,SUM(INM_NET_AMT) AS INM_NET_AMT, INM_DISC,SUM(INM_DISC_AMT) AS INM_DISC_AMT,SUM(INM_PACK_AMT) AS INM_PACK_AMT,SUM(INM_ACCESSIBLE_AMT) AS INM_ACCESSIBLE_AMT,INM_BEXCISE,SUM(INM_BE_AMT) AS INM_BE_AMT,INM_EDUC_CESS,SUM(INM_EDUC_AMT) AS INM_EDUC_AMT,INM_H_EDUC_CESS,SUM(INM_H_EDUC_AMT) AS INM_H_EDUC_AMT,SUM(INM_TAXABLE_AMT) AS INM_TAXABLE_AMT,INM_S_TAX,SUM(INM_S_TAX_AMT) As INM_S_TAX_AMT,SUM(INM_OTHER_AMT) AS INM_OTHER_AMT,SUM(INM_FREIGHT) AS INM_FREIGHT,SUM(INM_INSURANCE) AS INM_INSURANCE,SUM(INM_TRANS_AMT) AS INM_TRANS_AMT,SUM(INM_OCTRI_AMT) As INM_OCTRI_AMT,SUM(INM_ROUNDING_AMT) As INM_ROUNDING_AMT,SUM(INM_G_AMT) As INM_G_AMT,SUM(INM_TAX_TCS_AMT) As INM_TAX_TCS_AMT,INM_ISSUE_DATE,INM_REMOVAL_DATE,INM_ISSU_TIME,INM_REMOVEL_TIME,E_COMMODITY,I_UOM_NAME,INM_TAX_TCS,IND_AMORTAMT,IND_AMORTRATE,BD_QTY ,ROUND(BD_QTY*SUM(IND_INQTY),2) AS Weight,CH_QTY,IND_EX_AMT,IND_E_CESS_AMT,IND_SH_CESS_AMT FROM #temp GROUP BY I_CODE,P_CODE,P_GST_NO,E_TARIFF_NO,P_NAME,P_ADD1,P_VEND_CODE,P_CST,P_VAT,P_ECC_NO,INM_TNO,INM_NO,INM_DATE,INM_TRANSPORT,INM_VEH_NO,INM_LR_NO,INM_LR_DATE,I_NAME,CPOD_CUST_I_CODE,CPOD_CUST_I_NAME,CPOM_PONO,ST_TAX_NAME,CPOM_DATE,IND_SUBHEADING,IND_BACHNO,IND_NO_PACK,IND_PAK_QTY,  IND_RATE,  INM_DISC, INM_BEXCISE, INM_EDUC_CESS, INM_H_EDUC_CESS, INM_S_TAX, INM_ISSUE_DATE,INM_REMOVAL_DATE,INM_ISSU_TIME,INM_REMOVEL_TIME,E_COMMODITY,I_UOM_NAME,INM_TAX_TCS,IND_AMORTAMT,IND_AMORTRATE,BD_QTY,CH_QTY,IND_EX_AMT,IND_E_CESS_AMT,IND_SH_CESS_AMT Drop table #temp");
                    //weight calculation change: CH_QTY calculate as I_TARGET_WEIGHT* INVOICE_DETAIL.IND_INQTY 
                    dtfinal = CommonClasses.Execute("SELECT DISTINCT ITEM_MASTER.I_CODE,PARTY_MASTER.P_CODE,P_GST_NO,EXCISE_TARIFF_MASTER.E_TARIFF_NO, PARTY_MASTER.P_NAME, PARTY_MASTER.P_ADD1, PARTY_MASTER.P_VEND_CODE, PARTY_MASTER.P_CST, PARTY_MASTER.P_VAT, PARTY_MASTER.P_ECC_NO,  'JPDC'+CONVERT(varchar, LIM_NO)  as INM_TNO, LIM_NO as INM_NO, INVOICE_MASTER.INM_DATE, INVOICE_MASTER.INM_TRANSPORT, INVOICE_MASTER.INM_VEH_NO, INVOICE_MASTER.INM_LR_NO, INVOICE_MASTER.INM_LR_DATE, ITEM_MASTER.I_NAME, ITEM_MASTER.I_CODENO AS CPOD_CUST_I_CODE, INVOICE_DETAIL.IND_PACK_DESC AS CPOD_CUST_I_NAME, CUSTPO_MASTER.CPOM_PONO, SALES_TAX_MASTER.ST_TAX_NAME, CUSTPO_MASTER.CPOM_PO_DATE AS CPOM_DATE, INVOICE_DETAIL.IND_SUBHEADING, INVOICE_DETAIL.IND_BACHNO, INVOICE_DETAIL.IND_NO_PACK, CAST(ISNULL(INVOICE_DETAIL.IND_PAK_QTY, 0) AS numeric(20, 3)) AS IND_PAK_QTY, CAST(ISNULL(INVOICE_DETAIL.IND_INQTY, 0) AS numeric(20, 3)) AS IND_INQTY, CAST(ISNULL(INVOICE_DETAIL.IND_RATE, 0) AS numeric(20, 2)) AS IND_RATE, CAST(ISNULL(INVOICE_DETAIL.IND_AMT, 0) AS numeric(20, 2)) AS IND_AMT, CAST(ISNULL(INVOICE_MASTER.INM_NET_AMT, 0) AS numeric(20, 2)) AS INM_NET_AMT, CAST(ISNULL(INVOICE_MASTER.INM_DISC, 0) AS numeric(20, 2)) AS INM_DISC, CAST(ISNULL(INVOICE_MASTER.INM_DISC_AMT, 0) AS numeric(20, 2)) AS INM_DISC_AMT, CAST(ISNULL(INVOICE_MASTER.INM_PACK_AMT, 0) AS numeric(20, 2)) AS INM_PACK_AMT, CAST(ISNULL(INVOICE_MASTER.INM_ACCESSIBLE_AMT, 0) AS numeric(20, 2)) AS INM_ACCESSIBLE_AMT, CAST(ISNULL(INVOICE_MASTER.INM_BEXCISE, 0) AS numeric(20, 2)) AS INM_BEXCISE, CAST(ISNULL(INVOICE_MASTER.INM_BE_AMT, 0) AS numeric(20, 2)) AS INM_BE_AMT, CAST(ISNULL(INVOICE_MASTER.INM_EDUC_CESS, 0) AS numeric(20, 2)) AS INM_EDUC_CESS, CAST(ISNULL(INVOICE_MASTER.INM_EDUC_AMT, 0) AS numeric(20, 2)) AS INM_EDUC_AMT, CAST(ISNULL(INVOICE_MASTER.INM_H_EDUC_CESS, 0) AS numeric(20, 2)) AS INM_H_EDUC_CESS, CAST(ISNULL(INVOICE_MASTER.INM_H_EDUC_AMT, 0) AS numeric(20, 2)) AS INM_H_EDUC_AMT, CAST(ISNULL(INVOICE_MASTER.INM_TAXABLE_AMT, 0) AS numeric(20, 2)) AS INM_TAXABLE_AMT, CAST(ISNULL(INVOICE_MASTER.INM_S_TAX, 0) AS numeric(20, 2)) AS INM_S_TAX, CAST(ISNULL(INVOICE_MASTER.INM_S_TAX_AMT, 0) AS numeric(20, 2)) AS INM_S_TAX_AMT, CAST(ISNULL(INVOICE_MASTER.INM_OTHER_AMT, 0) AS numeric(20, 2)) AS INM_OTHER_AMT, CAST(ISNULL(INVOICE_MASTER.INM_FREIGHT, 0) AS numeric(20, 2)) AS INM_FREIGHT, CAST(ISNULL(INVOICE_MASTER.INM_INSURANCE, 0) AS numeric(20, 2)) AS INM_INSURANCE, CAST(ISNULL(INVOICE_MASTER.INM_TRANS_AMT, 0) AS numeric(20, 2)) AS INM_TRANS_AMT, CAST(ISNULL(INVOICE_MASTER.INM_OCTRI_AMT, 0) AS numeric(20, 2)) AS INM_OCTRI_AMT, CAST(ISNULL(INVOICE_MASTER.INM_ROUNDING_AMT, 0) AS numeric(20, 2)) AS INM_ROUNDING_AMT, CAST(ISNULL(INVOICE_MASTER.INM_G_AMT, 0) AS numeric(20, 2)) AS INM_G_AMT, CAST(ISNULL(INVOICE_MASTER.INM_TAX_TCS_AMT, 0) AS numeric(20, 2)) AS INM_TAX_TCS_AMT, INVOICE_MASTER.INM_ISSUE_DATE, INVOICE_MASTER.INM_REMOVAL_DATE, INVOICE_MASTER.INM_ISSU_TIME, INVOICE_MASTER.INM_REMOVEL_TIME, EXCISE_TARIFF_MASTER.E_COMMODITY, ITEM_UNIT_MASTER.I_UOM_NAME, INVOICE_MASTER.INM_TAX_TCS, ISNULL(INVOICE_DETAIL.IND_AMORTAMT, 0) AS IND_AMORTAMT, ISNULL(INVOICE_DETAIL.IND_AMORTRATE, 0) AS IND_AMORTRATE,ISNULL( I_TARGET_WEIGHT,0) AS BD_QTY, ROUND(ISNULL(I_TARGET_WEIGHT ,0) *  CAST(ISNULL(INVOICE_DETAIL.IND_INQTY, 0) AS numeric(20, 3)),2) AS CH_QTY,IND_EX_AMT as IND_EX_AMT,IND_E_CESS_AMT as IND_E_CESS_AMT,IND_SH_CESS_AMT as IND_SH_CESS_AMT ,IND_E_TARIFF_NO    ,SM_NAME,SM_STATE_CODE      into #temp FROM LABOR_INVOICE_MASTER INNER JOIN LABOR_INVOICE_DETAIL ON LABOR_INVOICE_MASTER.LIM_CODE = LABOR_INVOICE_DETAIL.LID_LIM_CODE INNER JOIN SALES_TAX_MASTER INNER JOIN INVOICE_DETAIL INNER JOIN INVOICE_MASTER ON INVOICE_DETAIL.IND_INM_CODE = INVOICE_MASTER.INM_CODE INNER JOIN PARTY_MASTER ON INVOICE_MASTER.INM_P_CODE = PARTY_MASTER.P_CODE INNER JOIN CUSTPO_MASTER INNER JOIN CUSTPO_DETAIL ON CUSTPO_MASTER.CPOM_CODE = CUSTPO_DETAIL.CPOD_CPOM_CODE ON INVOICE_MASTER.INM_P_CODE = CUSTPO_MASTER.CPOM_P_CODE AND INVOICE_DETAIL.IND_CPOM_CODE = CUSTPO_MASTER.CPOM_CODE AND INVOICE_DETAIL.IND_I_CODE = CUSTPO_DETAIL.CPOD_I_CODE AND INVOICE_DETAIL.IND_I_CODE = CUSTPO_DETAIL.CPOD_I_CODE INNER JOIN ITEM_MASTER ON INVOICE_DETAIL.IND_I_CODE = ITEM_MASTER.I_CODE INNER JOIN EXCISE_TARIFF_MASTER ON ITEM_MASTER.I_E_CODE = EXCISE_TARIFF_MASTER.E_CODE ON SALES_TAX_MASTER.ST_CODE = CUSTPO_DETAIL.CPOD_ST_CODE INNER JOIN ITEM_UNIT_MASTER ON ITEM_MASTER.I_UOM_CODE = ITEM_UNIT_MASTER.I_UOM_CODE ON LABOR_INVOICE_DETAIL.LID_INM_CODE = INVOICE_MASTER.INM_CODE AND LABOR_INVOICE_DETAIL.LID_I_CODE = INVOICE_DETAIL.IND_I_CODE   INNER JOIN STATE_MASTER ON P_SM_CODE=SM_CODE   WHERE (INVOICE_MASTER.INM_TYPE = 'OutJWINM') AND (INVOICE_MASTER.INM_CM_CODE = '" + Convert.ToInt32(Session["CompanyCode"]) + "') and LABOR_INVOICE_MASTER.ES_DELETE=0 AND LIM_CODE=" + code + " SELECT I_CODE,P_CODE,P_GST_NO,E_TARIFF_NO,P_NAME,P_ADD1,P_VEND_CODE,P_CST,P_VAT,P_ECC_NO,INM_TNO,INM_NO,INM_DATE,INM_TRANSPORT,INM_VEH_NO,INM_LR_NO,INM_LR_DATE,I_NAME,CPOD_CUST_I_CODE,CPOD_CUST_I_NAME,CPOM_PONO,ST_TAX_NAME,CPOM_DATE,IND_SUBHEADING,IND_BACHNO,IND_NO_PACK,IND_PAK_QTY,SUM(IND_INQTY) As IND_INQTY ,IND_RATE,SUM(IND_AMT) As IND_AMT,SUM(INM_NET_AMT) AS INM_NET_AMT, INM_DISC,SUM(INM_DISC_AMT) AS INM_DISC_AMT,SUM(INM_PACK_AMT) AS INM_PACK_AMT,SUM(INM_ACCESSIBLE_AMT) AS INM_ACCESSIBLE_AMT,INM_BEXCISE,SUM(INM_BE_AMT) AS INM_BE_AMT,INM_EDUC_CESS,SUM(INM_EDUC_AMT) AS INM_EDUC_AMT,INM_H_EDUC_CESS,SUM(INM_H_EDUC_AMT) AS INM_H_EDUC_AMT,SUM(INM_TAXABLE_AMT) AS INM_TAXABLE_AMT,INM_S_TAX,SUM(INM_S_TAX_AMT) As INM_S_TAX_AMT,SUM(INM_OTHER_AMT) AS INM_OTHER_AMT,SUM(INM_FREIGHT) AS INM_FREIGHT,SUM(INM_INSURANCE) AS INM_INSURANCE,SUM(INM_TRANS_AMT) AS INM_TRANS_AMT,SUM(INM_OCTRI_AMT) As INM_OCTRI_AMT,SUM(INM_ROUNDING_AMT) As INM_ROUNDING_AMT,SUM(INM_G_AMT) As INM_G_AMT,SUM(INM_TAX_TCS_AMT) As INM_TAX_TCS_AMT,INM_ISSUE_DATE,INM_REMOVAL_DATE,INM_ISSU_TIME,INM_REMOVEL_TIME,E_COMMODITY,I_UOM_NAME,INM_TAX_TCS,IND_AMORTAMT,IND_AMORTRATE,BD_QTY ,ROUND(BD_QTY*SUM(IND_INQTY),2) AS Weight,CH_QTY,IND_EX_AMT,IND_E_CESS_AMT,IND_SH_CESS_AMT ,IND_E_TARIFF_NO   ,SM_NAME,SM_STATE_CODE  FROM #temp GROUP BY I_CODE,P_CODE,P_GST_NO,E_TARIFF_NO,P_NAME,P_ADD1,P_VEND_CODE,P_CST,P_VAT,P_ECC_NO,INM_TNO,INM_NO,INM_DATE,INM_TRANSPORT,INM_VEH_NO,INM_LR_NO,INM_LR_DATE,I_NAME,CPOD_CUST_I_CODE,CPOD_CUST_I_NAME,CPOM_PONO,ST_TAX_NAME,CPOM_DATE,IND_SUBHEADING,IND_BACHNO,IND_NO_PACK,IND_PAK_QTY,  IND_RATE,  INM_DISC, INM_BEXCISE, INM_EDUC_CESS, INM_H_EDUC_CESS, INM_S_TAX, INM_ISSUE_DATE,INM_REMOVAL_DATE,INM_ISSU_TIME,INM_REMOVEL_TIME,E_COMMODITY,I_UOM_NAME,INM_TAX_TCS,IND_AMORTAMT,IND_AMORTRATE,BD_QTY,CH_QTY,IND_EX_AMT,IND_E_CESS_AMT,IND_SH_CESS_AMT  ,SM_NAME,SM_STATE_CODE,IND_E_TARIFF_NO Drop table #temp");
                }
                else
                    //Change Join I_E_CODE=E_CODE to INVOICE_DETAIL.IND_E_CODE=E_CODE(Wrong SAc No. getting in Labour C.I)
                    dtfinal = CommonClasses.Execute("SELECT DISTINCT(I_CODE),P_CODE,P_GST_NO,E_TARIFF_NO,E_TARIFF_NO AS IND_E_TARIFF_NO,P_NAME,P_ADD1,P_VEND_CODE,P_CST,P_VAT,P_ECC_NO,INM_TNO,INM_NO,INM_DATE,INM_TRANSPORT,INM_VEH_NO,INM_LR_NO,INM_LR_DATE,I_NAME,I_CODENO AS CPOD_CUST_I_CODE,IND_PACK_DESC as CPOD_CUST_I_NAME,CPOM_PONO,ST_TAX_NAME,CPOM_PO_DATE as CPOM_DATE,IND_SUBHEADING,IND_BACHNO,IND_NO_PACK,cast(isnull(IND_PAK_QTY,0) as numeric(20,3)) as IND_PAK_QTY,cast(isnull(IND_INQTY,0) as numeric(20,3)) as IND_INQTY,cast(isnull(IND_RATE,0) as numeric(20,2)) as IND_RATE,cast(isnull(IND_AMT,0) as numeric(20,2)) as IND_AMT,cast(isnull(INM_NET_AMT,0) as numeric(20,2)) as INM_NET_AMT,cast(isnull(INM_DISC,0) as numeric(20,2)) as INM_DISC,cast(isnull(INM_DISC_AMT,0) as numeric(20,2)) as INM_DISC_AMT,cast(isnull(INM_PACK_AMT,0) as numeric(20,2)) as INM_PACK_AMT,cast(isnull(INM_ACCESSIBLE_AMT,0) as numeric(20,2)) as INM_ACCESSIBLE_AMT,cast(isnull(INM_BEXCISE,0) as numeric(20,2)) as INM_BEXCISE,cast(isnull(INM_BE_AMT,0) as numeric(20,2)) as INM_BE_AMT,cast(isnull(INM_EDUC_CESS,0) as numeric(20,2)) as INM_EDUC_CESS,cast(isnull(INM_EDUC_AMT,0) as numeric(20,2)) as INM_EDUC_AMT,cast(isnull(INM_H_EDUC_CESS,0) as numeric(20,2)) as INM_H_EDUC_CESS,cast(isnull(INM_H_EDUC_AMT,0) as numeric(20,2)) as INM_H_EDUC_AMT,cast(isnull(INM_TAXABLE_AMT,0) as numeric(20,2)) as INM_TAXABLE_AMT,cast(isnull(INM_S_TAX,0) as numeric(20,2)) as INM_S_TAX,cast(isnull(INM_S_TAX_AMT,0) as numeric(20,2)) as INM_S_TAX_AMT,cast(isnull(INM_OTHER_AMT,0) as numeric(20,2)) as INM_OTHER_AMT,cast(isnull(INM_FREIGHT,0) as numeric(20,2)) as INM_FREIGHT,cast(isnull(INM_INSURANCE,0) as numeric(20,2)) as INM_INSURANCE,cast(isnull(INM_TRANS_AMT,0) as numeric(20,2)) as INM_TRANS_AMT,cast(isnull(INM_OCTRI_AMT,0) as numeric(20,2)) as INM_OCTRI_AMT,cast(isnull(INM_ROUNDING_AMT,0) as numeric(20,2)) as INM_ROUNDING_AMT,cast(isnull(INM_G_AMT,0) as numeric(20,2)) as INM_G_AMT,cast(isnull(INM_TAX_TCS_AMT,0) as numeric(20,2)) as INM_TAX_TCS_AMT,INM_ISSUE_DATE,INM_REMOVAL_DATE,INM_ISSU_TIME,INM_REMOVEL_TIME,EXCISE_TARIFF_MASTER.E_COMMODITY,ITEM_UNIT_MASTER.I_UOM_NAME,INM_TAX_TCS,ISNULL(IND_AMORTAMT,0) AS IND_AMORTAMT, ISNULL(IND_AMORTRATE,0) AS IND_AMORTRATE,IND_EX_AMT as IND_EX_AMT,IND_E_CESS_AMT as IND_E_CESS_AMT,IND_SH_CESS_AMT as IND_SH_CESS_AMT    ,AckNo,AckDate,InvValue,ReciptGSTIn,EInvStatus,IRN,ISNULL(QRCode,0) AS QRCodeEinvPrint,ISNULL(EwayBill,0) AS EwayBill ,SM_NAME,SM_STATE_CODE,IND_E_TARIFF_NO   FROM EXCISE_TARIFF_MASTER,CUSTPO_DETAIL,CUSTPO_MASTER,INVOICE_MASTER,INVOICE_DETAIL,ITEM_MASTER,SALES_TAX_MASTER,PARTY_MASTER,ITEM_UNIT_MASTER,STATE_MASTER WHERE INM_CODE = IND_INM_CODE and CPOD_CPOM_CODE = CPOM_CODE and INM_P_CODE = P_CODE AND INM_P_CODE = CPOM_P_CODE and CPOM_CODE = IND_CPOM_CODE AND IND_I_CODE=CPOD_I_CODE and IND_I_CODE = I_CODE AND INVOICE_DETAIL.IND_E_CODE=E_CODE and IND_I_CODE=CPOD_I_CODE  AND CPOD_ST_CODE=ST_CODE and INM_CODE='" + code + "' AND  INM_TYPE='OutJWINM' AND INM_CM_CODE='" + Convert.ToInt32(Session["CompanyCode"]) + "' and ITEM_UNIT_MASTER.I_UOM_CODE=ITEM_MASTER.I_UOM_CODE  AND P_SM_CODE=SM_CODE   --and I_E_CODE=E_CODE");
            }
            else
            {
                if (type == "1")
                {
                    dtfinal = CommonClasses.Execute("SELECT DISTINCT(I_CODE),P_CODE,SAC.E_TARIFF_NO,EXCISE_TARIFF_MASTER.E_TARIFF_NO AS SAC_CODE, P_NAME,P_ADD1,P_VEND_CODE,P_CST,P_VAT,P_ECC_NO,INM_TNO,INM_TNO,INM_NO,INM_DATE,INM_TRANSPORT,INM_VEH_NO,INM_LR_NO,INM_LR_DATE,I_NAME, I_CODENO AS CPOD_CUST_I_CODE,IND_PACK_DESC as CPOD_CUST_I_NAME,CPOM_PONO,ST_TAX_NAME,CPOM_PO_DATE as CPOM_DATE,IND_SUBHEADING,IND_BACHNO,IND_NO_PACK,cast(isnull(IND_PAK_QTY,0) as numeric(20,3)) as IND_PAK_QTY,cast(isnull(IND_INQTY,0) as numeric(20,3)) as IND_INQTY,cast(isnull(IND_RATE,0) as numeric(20,2)) as IND_RATE,cast(isnull(IND_AMT,0) as numeric(20,2)) as IND_AMT,cast(isnull(INM_NET_AMT,0) as numeric(20,2)) as INM_NET_AMT,cast(isnull(INM_DISC,0) as numeric(20,2)) as INM_DISC,cast(isnull(INM_DISC_AMT,0) as numeric(20,2)) as INM_DISC_AMT,cast(isnull(INM_PACK_AMT,0) as numeric(20,2)) as INM_PACK_AMT,cast(isnull(INM_ACCESSIBLE_AMT,0) as numeric(20,2)) as INM_ACCESSIBLE_AMT,cast(isnull(INM_BEXCISE,0) as numeric(20,2)) as INM_BEXCISE,cast(isnull(INM_BE_AMT,0) as numeric(20,2)) as INM_BE_AMT,cast(isnull(INM_EDUC_CESS,0) as numeric(20,2)) as INM_EDUC_CESS,cast(isnull(INM_EDUC_AMT,0) as numeric(20,2)) as INM_EDUC_AMT,cast(isnull(INM_H_EDUC_CESS,0) as numeric(20,2)) as INM_H_EDUC_CESS,cast(isnull(INM_H_EDUC_AMT,0) as numeric(20,2)) as INM_H_EDUC_AMT,cast(isnull(INM_TAXABLE_AMT,0) as numeric(20,2)) as INM_TAXABLE_AMT,cast(isnull(INM_S_TAX,0) as numeric(20,2)) as INM_S_TAX,cast(isnull(INM_S_TAX_AMT,0) as numeric(20,2)) as INM_S_TAX_AMT,cast(isnull(INM_OTHER_AMT,0) as numeric(20,2)) as INM_OTHER_AMT,cast(isnull(INM_FREIGHT,0) as numeric(20,2)) as INM_FREIGHT,cast(isnull(INM_INSURANCE,0) as numeric(20,2)) as INM_INSURANCE,cast(isnull(INM_TRANS_AMT,0) as numeric(20,2)) as INM_TRANS_AMT,cast(isnull(INM_OCTRI_AMT,0) as numeric(20,2)) as INM_OCTRI_AMT,cast(isnull(INM_ROUNDING_AMT,0) as numeric(20,2)) as INM_ROUNDING_AMT,cast(isnull(INM_G_AMT,0) as numeric(20,2)) as INM_G_AMT,cast(isnull(INM_TAX_TCS_AMT,0) as numeric(20,2)) as INM_TAX_TCS_AMT,INM_ISSUE_DATE,INM_REMOVAL_DATE,INM_ISSU_TIME,INM_REMOVEL_TIME,EXCISE_TARIFF_MASTER.E_COMMODITY,ITEM_UNIT_MASTER.I_UOM_NAME,INM_TAX_TCS,ISNULL(IND_AMORTAMT,0) AS IND_AMORTAMT, ISNULL(IND_AMORTRATE,0) AS IND_AMORTRATE,0 AS [HSN_NO] ,INM_ELECTRREFNUM,'' as INM_ADDRESS,'' as INM_STATE ,ISNULL(P_LBT_NO,'') AS P_GST_NO ,ISNULL( IND_EX_AMT,0) AS IND_EX_AMT,ISNULL(IND_E_CESS_AMT,0) AS IND_E_CESS_AMT,ISNULL(IND_SH_CESS_AMT,0) AS IND_SH_CESS_AMT ,INM_CODE,P_VEND_CODE,SM_NAME,SM_STATE_CODE,IND_E_TARIFF_NO    ,AckNo,AckDate,InvValue,ReciptGSTIn,EInvStatus,IRN,ISNULL(QRCode,0) AS QRCodeEinvPrint,ISNULL(EwayBill,0) AS EwayBill  FROM EXCISE_TARIFF_MASTER,CUSTPO_DETAIL,CUSTPO_MASTER,INVOICE_MASTER,INVOICE_DETAIL,ITEM_MASTER,SALES_TAX_MASTER,PARTY_MASTER,ITEM_UNIT_MASTER,STATE_MASTER,EXCISE_TARIFF_MASTER SAC WHERE INM_CODE = IND_INM_CODE and CPOD_CPOM_CODE = CPOM_CODE and INM_P_CODE = P_CODE AND INM_P_CODE = CPOM_P_CODE and CPOM_CODE = IND_CPOM_CODE AND IND_I_CODE=CPOD_I_CODE and IND_I_CODE = I_CODE and I_E_CODE=SAC.E_CODE and IND_E_CODE=EXCISE_TARIFF_MASTER.E_CODE  and IND_I_CODE=CPOD_I_CODE  AND CPOD_ST_CODE=ST_CODE and ITEM_UNIT_MASTER.I_UOM_CODE=ITEM_MASTER.I_UOM_CODE AND INVOICE_MASTER.ES_DELETE=0  AND  INM_TYPE='OutJWINM' AND INM_CM_CODE='" + Convert.ToInt32(Session["CompanyCode"]) + "' AND P_SM_CODE=SM_CODE  and INM_NO BETWEEN '" + invoice_code + "' AND '" + reportType + "'");
                }

                else if (type == "2")
                {
                    dtfinal = CommonClasses.Execute("SELECT DISTINCT(I_CODE),P_CODE,E_TARIFF_NO,P_NAME,P_ADD1,P_VEND_CODE,P_CST,P_VAT,P_ECC_NO,INM_TNO,INM_NO,INM_DATE,INM_TRANSPORT,INM_VEH_NO,INM_LR_NO,INM_LR_DATE,I_NAME, I_CODENO AS CPOD_CUST_I_CODE,IND_PACK_DESC as CPOD_CUST_I_NAME,CPOM_PONO,ST_TAX_NAME,CPOM_PO_DATE as CPOM_DATE,IND_SUBHEADING,IND_BACHNO,IND_NO_PACK,cast(isnull(IND_PAK_QTY,0) as numeric(20,3)) as IND_PAK_QTY,cast(isnull(IND_INQTY,0) as numeric(20,3)) as IND_INQTY,cast(isnull(IND_RATE,0) as numeric(20,2)) as IND_RATE,cast(isnull(IND_AMT,0) as numeric(20,2)) as IND_AMT,cast(isnull(INM_NET_AMT,0) as numeric(20,2)) as INM_NET_AMT,cast(isnull(INM_DISC,0) as numeric(20,2)) as INM_DISC,cast(isnull(INM_DISC_AMT,0) as numeric(20,2)) as INM_DISC_AMT,cast(isnull(INM_PACK_AMT,0) as numeric(20,2)) as INM_PACK_AMT,cast(isnull(INM_ACCESSIBLE_AMT,0) as numeric(20,2)) as INM_ACCESSIBLE_AMT,cast(isnull(INM_BEXCISE,0) as numeric(20,2)) as INM_BEXCISE,cast(isnull(INM_BE_AMT,0) as numeric(20,2)) as INM_BE_AMT,cast(isnull(INM_EDUC_CESS,0) as numeric(20,2)) as INM_EDUC_CESS,cast(isnull(INM_EDUC_AMT,0) as numeric(20,2)) as INM_EDUC_AMT,cast(isnull(INM_H_EDUC_CESS,0) as numeric(20,2)) as INM_H_EDUC_CESS,cast(isnull(INM_H_EDUC_AMT,0) as numeric(20,2)) as INM_H_EDUC_AMT,cast(isnull(INM_TAXABLE_AMT,0) as numeric(20,2)) as INM_TAXABLE_AMT,cast(isnull(INM_S_TAX,0) as numeric(20,2)) as INM_S_TAX,cast(isnull(INM_S_TAX_AMT,0) as numeric(20,2)) as INM_S_TAX_AMT,cast(isnull(INM_OTHER_AMT,0) as numeric(20,2)) as INM_OTHER_AMT,cast(isnull(INM_FREIGHT,0) as numeric(20,2)) as INM_FREIGHT,cast(isnull(INM_INSURANCE,0) as numeric(20,2)) as INM_INSURANCE,cast(isnull(INM_TRANS_AMT,0) as numeric(20,2)) as INM_TRANS_AMT,cast(isnull(INM_OCTRI_AMT,0) as numeric(20,2)) as INM_OCTRI_AMT,cast(isnull(INM_ROUNDING_AMT,0) as numeric(20,2)) as INM_ROUNDING_AMT,cast(isnull(INM_G_AMT,0) as numeric(20,2)) as INM_G_AMT,cast(isnull(INM_TAX_TCS_AMT,0) as numeric(20,2)) as INM_TAX_TCS_AMT,INM_ISSUE_DATE,INM_REMOVAL_DATE,INM_ISSU_TIME,INM_REMOVEL_TIME,EXCISE_TARIFF_MASTER.E_COMMODITY,ITEM_UNIT_MASTER.I_UOM_NAME,INM_TAX_TCS,ISNULL(IND_AMORTAMT,0) AS IND_AMORTAMT, ISNULL(IND_AMORTRATE,0) AS IND_AMORTRATE,0 AS [HSN_NO] ,INM_ELECTRREFNUM,'' as INM_ADDRESS,'' as INM_STATE ,ISNULL(P_LBT_NO,'') AS P_GST_NO ,ISNULL( IND_EX_AMT,0) AS IND_EX_AMT,ISNULL(IND_E_CESS_AMT,0) AS IND_E_CESS_AMT,ISNULL(IND_SH_CESS_AMT,0) AS IND_SH_CESS_AMT ,INM_CODE,P_VEND_CODE,SM_NAME,SM_STATE_CODE,IND_E_TARIFF_NO     ,AckNo,AckDate,InvValue,ReciptGSTIn,EInvStatus,IRN,ISNULL(QRCode,0) AS QRCodeEinvPrint,ISNULL(EwayBill,0) AS EwayBill   FROM EXCISE_TARIFF_MASTER,CUSTPO_DETAIL,CUSTPO_MASTER,INVOICE_MASTER,INVOICE_DETAIL,ITEM_MASTER,SALES_TAX_MASTER,PARTY_MASTER,ITEM_UNIT_MASTER,STATE_MASTER WHERE INM_CODE = IND_INM_CODE and CPOD_CPOM_CODE = CPOM_CODE and INM_P_CODE = P_CODE AND INM_P_CODE = CPOM_P_CODE and CPOM_CODE = IND_CPOM_CODE AND IND_I_CODE=CPOD_I_CODE and IND_I_CODE = I_CODE and IND_E_CODE=E_CODE and IND_I_CODE=CPOD_I_CODE  AND CPOD_ST_CODE=ST_CODE and ITEM_UNIT_MASTER.I_UOM_CODE=ITEM_MASTER.I_UOM_CODE AND INVOICE_MASTER.ES_DELETE=0  AND  INM_TYPE='OutJWINM' AND INM_CM_CODE='" + Convert.ToInt32(Session["CompanyCode"]) + "'  AND P_SM_CODE=SM_CODE  and INM_NO BETWEEN '" + invoice_code + "' AND '" + reportType + "'");
                }
                else
                {
                    dtfinal = CommonClasses.Execute("SELECT DISTINCT(I_CODE),P_CODE,IND_E_TARIFF_NO AS E_TARIFF_NO,IND_E_TARIFF_NO AS IND_E_TARIFF_NO,P_NAME,P_ADD1,P_VEND_CODE,P_CST,P_VAT,P_ECC_NO,INM_TNO,INM_NO,INM_DATE,INM_TRANSPORT,INM_VEH_NO,INM_LR_NO,INM_LR_DATE,I_NAME, I_CODENO AS CPOD_CUST_I_CODE,IND_PACK_DESC as CPOD_CUST_I_NAME,CPOM_PONO,ST_TAX_NAME,CPOM_PO_DATE as CPOM_DATE,IND_SUBHEADING,IND_BACHNO,IND_NO_PACK,cast(isnull(IND_PAK_QTY,0) as numeric(20,3)) as IND_PAK_QTY,cast(isnull(IND_INQTY,0) as numeric(20,3)) as IND_INQTY,cast(isnull(IND_RATE,0) as numeric(20,2)) as IND_RATE,cast(isnull(IND_AMT,0) as numeric(20,2)) as IND_AMT,cast(isnull(INM_NET_AMT,0) as numeric(20,2)) as INM_NET_AMT,cast(isnull(INM_DISC,0) as numeric(20,2)) as INM_DISC,cast(isnull(INM_DISC_AMT,0) as numeric(20,2)) as INM_DISC_AMT,cast(isnull(INM_PACK_AMT,0) as numeric(20,2)) as INM_PACK_AMT,cast(isnull(INM_ACCESSIBLE_AMT,0) as numeric(20,2)) as INM_ACCESSIBLE_AMT,cast(isnull(INM_BEXCISE,0) as numeric(20,2)) as INM_BEXCISE,cast(isnull(INM_BE_AMT,0) as numeric(20,2)) as INM_BE_AMT,cast(isnull(INM_EDUC_CESS,0) as numeric(20,2)) as INM_EDUC_CESS,cast(isnull(INM_EDUC_AMT,0) as numeric(20,2)) as INM_EDUC_AMT,cast(isnull(INM_H_EDUC_CESS,0) as numeric(20,2)) as INM_H_EDUC_CESS,cast(isnull(INM_H_EDUC_AMT,0) as numeric(20,2)) as INM_H_EDUC_AMT,cast(isnull(INM_TAXABLE_AMT,0) as numeric(20,2)) as INM_TAXABLE_AMT,cast(isnull(INM_S_TAX,0) as numeric(20,2)) as INM_S_TAX,cast(isnull(INM_S_TAX_AMT,0) as numeric(20,2)) as INM_S_TAX_AMT,cast(isnull(INM_OTHER_AMT,0) as numeric(20,2)) as INM_OTHER_AMT,cast(isnull(INM_FREIGHT,0) as numeric(20,2)) as INM_FREIGHT,cast(isnull(INM_INSURANCE,0) as numeric(20,2)) as INM_INSURANCE,cast(isnull(INM_TRANS_AMT,0) as numeric(20,2)) as INM_TRANS_AMT,cast(isnull(INM_OCTRI_AMT,0) as numeric(20,2)) as INM_OCTRI_AMT,cast(isnull(INM_ROUNDING_AMT,0) as numeric(20,2)) as INM_ROUNDING_AMT,cast(isnull(INM_G_AMT,0) as numeric(20,2)) as INM_G_AMT,cast(isnull(INM_TAX_TCS_AMT,0) as numeric(20,2)) as INM_TAX_TCS_AMT,INM_ISSUE_DATE,INM_REMOVAL_DATE,INM_ISSU_TIME,INM_REMOVEL_TIME,EXCISE_TARIFF_MASTER.E_COMMODITY,ITEM_UNIT_MASTER.I_UOM_NAME,INM_TAX_TCS,ISNULL(IND_AMORTAMT,0) AS IND_AMORTAMT, ISNULL(IND_AMORTRATE,0) AS IND_AMORTRATE,0 AS [HSN_NO] ,INM_ELECTRREFNUM,'' as INM_ADDRESS,'' as INM_STATE ,ISNULL(P_LBT_NO,'') AS P_GST_NO ,ISNULL( IND_EX_AMT,0) AS IND_EX_AMT,ISNULL(IND_E_CESS_AMT,0) AS IND_E_CESS_AMT,ISNULL(IND_SH_CESS_AMT,0) AS IND_SH_CESS_AMT ,INM_CODE,P_VEND_CODE,SM_NAME,SM_STATE_CODE,IND_E_TARIFF_NO  FROM EXCISE_TARIFF_MASTER,CUSTPO_DETAIL,CUSTPO_MASTER,INVOICE_MASTER,INVOICE_DETAIL,ITEM_MASTER,SALES_TAX_MASTER,PARTY_MASTER,ITEM_UNIT_MASTER,STATE_MASTER WHERE INM_CODE = IND_INM_CODE and CPOD_CPOM_CODE = CPOM_CODE and INM_P_CODE = P_CODE AND INM_P_CODE = CPOM_P_CODE and CPOM_CODE = IND_CPOM_CODE AND IND_I_CODE=CPOD_I_CODE and IND_I_CODE = I_CODE and IND_E_CODE=E_CODE and IND_I_CODE=CPOD_I_CODE  AND CPOD_ST_CODE=ST_CODE and ITEM_UNIT_MASTER.I_UOM_CODE=ITEM_MASTER.I_UOM_CODE AND INVOICE_MASTER.ES_DELETE=0  AND  INM_TYPE='OutJWINM' AND INM_CM_CODE='" + Convert.ToInt32(Session["CompanyCode"]) + "'  AND P_SM_CODE=SM_CODE  and INM_NO BETWEEN '" + invoice_code + "' AND '" + reportType + "'");
                }
            }
            DataTable dtCompGSTNo = CommonClasses.Execute("SELECT CM_GST_NO,SM_NAME,CM_NAME,CM_ADDRESS1 FROM COMPANY_MASTER,STATE_MASTER where SM_CODE=CM_STATE AND  CM_ID=" + Session["CompanyId"].ToString() + " AND  CM_CODE='" + Convert.ToInt32(Session["CompanyCode"]) + "'");

            if (dtfinal.Rows.Count > 0)
            {

                 //dtfinal.Columns.Add("QRCodeEinv", typeof(byte[])); 

                 //   foreach (DataRow row in dtfinal.Rows)
                 //   {
                 //       string strEQR = row["QRCodeEinvPrint"].ToString();
                 //       var Ewriter = new BarcodeWriter();
                 //       Ewriter.Format = BarcodeFormat.QR_CODE;
                 //       var Eresult = Ewriter.Write(strEQR);
                 //       string Epath = Server.MapPath("~/UpLoadPath/QR/QRCodeEinv.Jpeg");
                 //       var EbarcodeBitmap = new Bitmap(Eresult);

                 //       byte[] Ebytes;
                 //       using (MemoryStream Ememory = new MemoryStream())
                 //       {
                 //           using (FileStream efs = new FileStream(Epath, FileMode.Create, FileAccess.ReadWrite))
                 //           {
                 //               EbarcodeBitmap.Save(Ememory, System.Drawing.Imaging.ImageFormat.Png);

                 //               Ebytes = Ememory.ToArray();
                 //               efs.Write(Ebytes, 0, Ebytes.Length);
                 //           }
                 //       }
                 //       row["QRCodeEinv"] = (byte[])Ebytes;
                 //   }
                ReportDocument rptname = null;
                rptname = new ReportDocument();
                if (Cond == "1")
                {
                    rptname.Load(Server.MapPath("~/Reports/rptTaxInvoice_1.rpt"));
                    rptname.FileName = Server.MapPath("~/Reports/rptTaxInvoice_1.rpt");

                    rptname.Refresh();
                    rptname.SetDataSource(dtfinal);
                    rptname.SetParameterValue("txtCompPhone", Session["CompanyPhone"].ToString());
                    rptname.SetParameterValue("txtCompFaxNo", Session["Companyfax"].ToString());
                    rptname.SetParameterValue("txtCompVatTin", Session["CompanyVatTin"].ToString());
                    rptname.SetParameterValue("txtCompCstTin", Session["CompanyCstTin"].ToString());
                    rptname.SetParameterValue("txtCompEcc", Session["CompanyEccNo"].ToString());
                    rptname.SetParameterValue("txtCompVatWef", Convert.ToDateTime(Session["CompanyVatWef"].ToString()).ToShortDateString());
                    rptname.SetParameterValue("txtCompCstWef", Convert.ToDateTime(Session["CompanyCstWef"].ToString()).ToShortDateString());
                    rptname.SetParameterValue("txtCompIso", Session["CompanyIso"].ToString());
                    rptname.SetParameterValue("txtCompRegd", Session["CompanyRegd"].ToString());
                    rptname.SetParameterValue("txtCompWebsite", Session["CompanyWebsite"].ToString());
                    rptname.SetParameterValue("txtCompEmail", Session["CompanyEmail"].ToString());
                    rptname.SetParameterValue("txtCompFinancialYr", Session["CompanyFinancialYr"].ToString());
                    //string IsoNo = DL_DBAccess.GetColumn("select ISO_NO from ISONO_MASTER,INVOICE_MASTER where INM_CODE='" + code + "' and ISO_SCREEN_NO=81 and INM_DATE<=ISO_WEF_DATE and INM_DATE>=ISO_WEF_DATE");
                    //string CINNo = DL_DBAccess.GetColumn("select CM_CIN_NO from COMPANY_MASTER where CM_ID='" + Session["CompanyId"] + "'");
                    rptname.SetParameterValue("txtCINNo", dtCompGSTNo.Rows[0]["SM_NAME"].ToString());
                    //  rptname.SetParameterValue("txtSAC", dtfinal.Rows[0]["SAC_CODE"].ToString());
                }
                else if (Cond == "3")
                {
                    rptname.Load(Server.MapPath("~/Reports/rptTaxInvoice.rpt"));
                    rptname.FileName = Server.MapPath("~/Reports/rptTaxInvoice.rpt");

                    rptname.Refresh();
                    rptname.SetDataSource(dtfinal);
                    rptname.SetParameterValue("txtCompPhone", Session["CompanyPhone"].ToString());
                    rptname.SetParameterValue("txtCompFaxNo", Session["Companyfax"].ToString());
                    rptname.SetParameterValue("txtCompVatTin", Session["CompanyVatTin"].ToString());
                    rptname.SetParameterValue("txtCompCstTin", Session["CompanyCstTin"].ToString());
                    rptname.SetParameterValue("txtCompEcc", Session["CompanyEccNo"].ToString());
                    rptname.SetParameterValue("txtCompVatWef", Convert.ToDateTime(Session["CompanyVatWef"].ToString()).ToShortDateString());
                    rptname.SetParameterValue("txtCompCstWef", Convert.ToDateTime(Session["CompanyCstWef"].ToString()).ToShortDateString());
                    rptname.SetParameterValue("txtCompIso", Session["CompanyIso"].ToString());
                    rptname.SetParameterValue("txtCompRegd", Session["CompanyRegd"].ToString());
                    rptname.SetParameterValue("txtCompWebsite", Session["CompanyWebsite"].ToString());
                    rptname.SetParameterValue("txtCompEmail", Session["CompanyEmail"].ToString());
                    rptname.SetParameterValue("txtCompFinancialYr", Session["CompanyFinancialYr"].ToString());
                    //string IsoNo = DL_DBAccess.GetColumn("select ISO_NO from ISONO_MASTER,INVOICE_MASTER where INM_CODE='" + code + "' and ISO_SCREEN_NO=81 and INM_DATE<=ISO_WEF_DATE and INM_DATE>=ISO_WEF_DATE");
                    //string CINNo = DL_DBAccess.GetColumn("select CM_CIN_NO from COMPANY_MASTER where CM_ID='" + Session["CompanyId"] + "'");
                    rptname.SetParameterValue("txtCINNo", dtCompGSTNo.Rows[0]["SM_NAME"].ToString());
                    //rptname.SetParameterValue("txtSAC", dtfinal.Rows[0]["SAC_CODE"].ToString());
                }
                else if (Cond == "2")
                {
                    DataTable dtTaxInvoiceGST = new DataTable();
                    dtTaxInvoiceGST = dtfinal;

                    DataTable dtTemp = new DataTable();
                    DataSet dsTaxInvoiceGST = new DataSet();
                    dtTemp.Columns.Add("INM_CODE", typeof(int));
                    dtTemp.Columns.Add("INM_NO", typeof(int));
                    dtTemp.Columns.Add("INM_NAME", typeof(string));
                    dtTemp.Columns.Add("INM_SEQNO", typeof(int));

                    if (chkPrint1 == "1")
                    {
                        DataRow dr = dtTemp.NewRow();
                        dr["INM_CODE"] = code;
                        dr["INM_NO"] = 1;
                        dr["INM_NAME"] = "Original For Recipient";
                        dr["INM_SEQNO"] = 1;
                        dtTemp.Rows.Add(dr);
                    }
                    if (chkPrint1 == "2")
                    {
                        DataRow dr = dtTemp.NewRow();
                        dr["INM_CODE"] = code;
                        dr["INM_NO"] = 1;
                        dr["INM_NAME"] = "Original For Recipient";
                        dr["INM_SEQNO"] = 1;
                        dtTemp.Rows.Add(dr);

                        dr = dtTemp.NewRow();
                        dr["INM_CODE"] = code;
                        dr["INM_NO"] = 1;
                        dr["INM_NAME"] = "Duplicate For Transporter";
                        dr["INM_SEQNO"] = 2;
                        dtTemp.Rows.Add(dr);
                    }
                    if (chkPrint1 == "3")
                    {
                        DataRow dr = dtTemp.NewRow();
                        dr["INM_CODE"] = code;
                        dr["INM_NO"] = 1;
                        dr["INM_NAME"] = "Original For Recipient";
                        dr["INM_SEQNO"] = 1;
                        dtTemp.Rows.Add(dr);

                        dr = dtTemp.NewRow();
                        dr["INM_CODE"] = code;
                        dr["INM_NO"] = 1;
                        dr["INM_NAME"] = "Duplicate For Transporter";
                        dr["INM_SEQNO"] = 2;
                        dtTemp.Rows.Add(dr);

                        dr = dtTemp.NewRow();
                        dr["INM_CODE"] = code;
                        dr["INM_NO"] = 1;
                        dr["INM_NAME"] = "Triplicate for Supplier";
                        dr["INM_SEQNO"] = 3;
                        dtTemp.Rows.Add(dr);
                    }
                    if (chkPrint1 == "4")
                    {
                        DataRow dr = dtTemp.NewRow();

                        dr["INM_CODE"] = code;
                        dr["INM_NO"] = 1;
                        dr["INM_NAME"] = "Original For Recipient";
                        dr["INM_SEQNO"] = 1;
                        dtTemp.Rows.Add(dr);

                        dr = dtTemp.NewRow();
                        dr["INM_CODE"] = code;
                        dr["INM_NO"] = 1;
                        dr["INM_NAME"] = "Duplicate For Transporter";
                        dr["INM_SEQNO"] = 2;
                        dtTemp.Rows.Add(dr);

                        dr = dtTemp.NewRow();
                        dr["INM_CODE"] = code;
                        dr["INM_NO"] = 1;
                        dr["INM_NAME"] = "Triplicate for Supplier";
                        dr["INM_SEQNO"] = 3;
                        dtTemp.Rows.Add(dr);

                        dr = dtTemp.NewRow();
                        dr["INM_CODE"] = code;
                        dr["INM_NO"] = 1;
                        dr["INM_NAME"] = "Quaradruplicate";
                        dr["INM_SEQNO"] = 4;
                        dtTemp.Rows.Add(dr);
                    }
                    dsTaxInvoiceGST.Tables.Add(dtTaxInvoiceGST);
                    dsTaxInvoiceGST.Tables[0].TableName = "dtTaxInvoiceGST";
                    DataTable dta = new DataTable();
                    dta = (DataTable)dtTemp;
                    dsTaxInvoiceGST.Tables.Add(dta);
                    dsTaxInvoiceGST.Tables[1].TableName = "NoOfCopyTaxInvoice";
                    string PType = Convert.ToInt32(Request.QueryString[2]).ToString();
                    if (PType == "1")
                    {
                        rptname.Load(Server.MapPath("~/Reports/rptTaxInvoiceGSTLabour2.rpt"));//rptTaxInvoiceGSTLabour.rpt
                        rptname.FileName = Server.MapPath("~/Reports/rptTaxInvoiceGSTLabour2.rpt");
                    }
                    else
                    {
                        if (FrmDelieveryChallanFlag.Equals("1"))
                        {
                            rptname.Load(Server.MapPath("~/Reports/rptTaxInvoiceGSTLabour2.rpt"));//rptTaxInvoiceGSTLabour1.rpt
                            rptname.FileName = Server.MapPath("~/Reports/rptTaxInvoiceGSTLabour2.rpt");
                        }
                        else
                        {
                            rptname.Load(Server.MapPath("~/Reports/rptTaxInvoiceGSTLabour1.rpt"));//rptTaxInvoiceGSTLabour1.rpt
                            rptname.FileName = Server.MapPath("~/Reports/rptTaxInvoiceGSTLabour1.rpt");
                        }
                    }
                    rptname.SetDataSource(dsTaxInvoiceGST);
                    rptname.SetParameterValue("txtCompName", dtCompGSTNo.Rows[0]["CM_NAME"].ToString());
                    rptname.SetParameterValue("txtCompAdd", dtCompGSTNo.Rows[0]["CM_ADDRESS1"].ToString());
                    rptname.SetParameterValue("txtCompGSTNo", dtCompGSTNo.Rows[0]["CM_GST_NO"].ToString());
                    rptname.SetParameterValue("txtCompCity", dtCompGSTNo.Rows[0]["SM_NAME"].ToString());
                    rptname.SetParameterValue("txtFrmDelieveryChallanFlag", FrmDelieveryChallanFlag);
                }
                else
                {
                    DataTable dtTaxInvoiceGST = new DataTable();
                    dtTaxInvoiceGST = dtfinal;

                    DataTable dtTemp = new DataTable();
                    DataSet dsTaxInvoiceGST = new DataSet();
                    dtTemp.Columns.Add("INM_CODE", typeof(int));
                    dtTemp.Columns.Add("INM_NO", typeof(int));
                    dtTemp.Columns.Add("INM_NAME", typeof(string));
                    dtTemp.Columns.Add("INM_SEQNO", typeof(int));

                    if (chkPrint1 == "1")
                    {
                        DataRow dr = dtTemp.NewRow();
                        dr["INM_CODE"] = code;
                        dr["INM_NO"] = 1;
                        dr["INM_NAME"] = "Original For Recipient";
                        dr["INM_SEQNO"] = 1;
                        dtTemp.Rows.Add(dr);
                    }
                    if (chkPrint1 == "2")
                    {
                        DataRow dr = dtTemp.NewRow();
                        dr["INM_CODE"] = code;
                        dr["INM_NO"] = 1;
                        dr["INM_NAME"] = "Original For Recipient";
                        dr["INM_SEQNO"] = 1;
                        dtTemp.Rows.Add(dr);

                        dr = dtTemp.NewRow();
                        dr["INM_CODE"] = code;
                        dr["INM_NO"] = 1;
                        dr["INM_NAME"] = "Duplicate For Transporter";
                        dr["INM_SEQNO"] = 2;
                        dtTemp.Rows.Add(dr);
                    }
                    if (chkPrint1 == "3")
                    {
                        DataRow dr = dtTemp.NewRow();
                        dr["INM_CODE"] = code;
                        dr["INM_NO"] = 1;
                        dr["INM_NAME"] = "Original For Recipient";
                        dr["INM_SEQNO"] = 1;
                        dtTemp.Rows.Add(dr);

                        dr = dtTemp.NewRow();
                        dr["INM_CODE"] = code;
                        dr["INM_NO"] = 1;
                        dr["INM_NAME"] = "Duplicate For Transporter";
                        dr["INM_SEQNO"] = 2;
                        dtTemp.Rows.Add(dr);

                        dr = dtTemp.NewRow();
                        dr["INM_CODE"] = code;
                        dr["INM_NO"] = 1;
                        dr["INM_NAME"] = "Triplicate for Supplier";
                        dr["INM_SEQNO"] = 3;
                        dtTemp.Rows.Add(dr);
                    }
                    if (chkPrint1 == "4")
                    {
                        DataRow dr = dtTemp.NewRow();

                        dr["INM_CODE"] = code;
                        dr["INM_NO"] = 1;
                        dr["INM_NAME"] = "Original For Recipient";
                        dr["INM_SEQNO"] = 1;
                        dtTemp.Rows.Add(dr);

                        dr = dtTemp.NewRow();
                        dr["INM_CODE"] = code;
                        dr["INM_NO"] = 1;
                        dr["INM_NAME"] = "Duplicate For Transporter";
                        dr["INM_SEQNO"] = 2;
                        dtTemp.Rows.Add(dr);

                        dr = dtTemp.NewRow();
                        dr["INM_CODE"] = code;
                        dr["INM_NO"] = 1;
                        dr["INM_NAME"] = "Triplicate for Supplier";
                        dr["INM_SEQNO"] = 3;
                        dtTemp.Rows.Add(dr);

                        dr = dtTemp.NewRow();
                        dr["INM_CODE"] = code;
                        dr["INM_NO"] = 1;
                        dr["INM_NAME"] = "Quaradruplicate";
                        dr["INM_SEQNO"] = 4;
                        dtTemp.Rows.Add(dr);
                    }
                    dsTaxInvoiceGST.Tables.Add(dtTaxInvoiceGST);
                    dsTaxInvoiceGST.Tables[0].TableName = "dtTaxInvoiceGST";
                    DataTable dta = new DataTable();
                    dta = (DataTable)dtTemp;
                    dsTaxInvoiceGST.Tables.Add(dta);
                    dsTaxInvoiceGST.Tables[1].TableName = "NoOfCopyTaxInvoice";
                    string PType = Convert.ToInt32(Request.QueryString[2]).ToString();


                    rptname.Load(Server.MapPath("~/Reports/rptTaxEInvoiceGSTLabour.rpt"));//rptTaxInvoiceGSTLabour1.rpt
                    rptname.FileName = Server.MapPath("~/Reports/rptTaxEInvoiceGSTLabour.rpt");

                    rptname.SetDataSource(dsTaxInvoiceGST);
                    rptname.SetParameterValue("txtCompName", dtCompGSTNo.Rows[0]["CM_NAME"].ToString());
                    rptname.SetParameterValue("txtCompAdd", dtCompGSTNo.Rows[0]["CM_ADDRESS1"].ToString());
                    rptname.SetParameterValue("txtCompGSTNo", dtCompGSTNo.Rows[0]["CM_GST_NO"].ToString());
                    rptname.SetParameterValue("txtCompCity", dtCompGSTNo.Rows[0]["SM_NAME"].ToString());
                    rptname.SetParameterValue("txtFrmDelieveryChallanFlag", FrmDelieveryChallanFlag);
                }
                rptname.SetParameterValue("txtFrmDelieveryChallanFlag", FrmDelieveryChallanFlag);
                CrystalReportViewer1.ReportSource = rptname;
            }
        }
        catch (Exception Ex)
        {
            CommonClasses.SendError("Tax Invoice", "GenerateReport", Ex.Message);
        }
    }
    #endregion



    #region btnCancel_Click
    protected void btnCancel_Click(object sender, EventArgs e)
    {
        if (Request.QueryString[6] == "1")
        {
            Response.Redirect("~/Transactions/VIEW/ViewLabourChargeInvoiceNew.aspx", false);
        }
        else
        {
            Response.Redirect("~/Transactions/VIEW/ViewLabourChargeInvoice.aspx", false);
        }
    }
    #endregion
}
